/* Generated by remu-casegen. Do not edit by hand.
* case: case_0046
* name: crc16-ccitt--compare-select-rotate-mix-add-carry-02e
* category: checksums
* structural signature: compare-select,rotate-mix,add-carry,sub-borrow,multiply-low,horner-loop,compare-select,carry-chain,horner-loop,sub-borrow,minmax-clamp,compare-select
* inspiration: https://github.com/embench/embench-iot
* kernel expected: 0x0000e907
* expected: 0x39e99e3c
* Contract: freestanding ISO C unsigned arithmetic; no undefined behavior.
*/
typedef unsigned int u32;
typedef unsigned short u16;
typedef unsigned char u8;

static volatile u32 input[16] = { 0xe331b8c8u, 0xdfb9704fu, 0x4f358166u, 0x80000000u, 0x8a2ec39du, 0x80000000u, 0x12f8efc2u, 0xdbdc6aebu, 0x6324b07bu, 0x295f29a2u, 0xc26a7499u, 0xb5851573u, 0x298b2feeu, 0x4d7580d0u, 0xcbb45a4au, 0x81b63110u };

__attribute__((noinline)) static u32 remu_kernel(void)
{
    u16 crc = (u16)input[15] ^ (u16)0xffffu;
    for (u32 i = 0u; i < 13u; ++i) {
        crc = (u16)(crc ^ ((u16)(u8)input[i] << 8u));
        for (u32 bit = 0u; bit < 8u; ++bit)
            crc = (crc & 0x8000u) ? (u16)((u16)(crc << 1u) ^ 0x1021u) : (u16)(crc << 1u);
    }
    return (u32)crc;
}

#ifdef REMU_KERNEL_ONLY
__attribute__((noinline, used)) u32 remu_case(void)
{
    return remu_kernel();
}
#else
__attribute__((noinline, used)) u32 remu_case(void)
{
    u32 r[6];
    u32 memory[8];
    r[0] = remu_kernel();
    r[1] = input[15];
    r[2] = input[3];
    r[3] = input[7];
    r[4] = input[11];
    r[5] = 0x6df7df3eu;
    memory[0] = input[0] ^ 0x0000002eu;
    memory[1] = input[1] ^ 0x0000005cu;
    memory[2] = input[2] ^ 0x000000b8u;
    memory[3] = input[3] ^ 0x00000170u;
    memory[4] = input[4] ^ 0x000002e0u;
    memory[5] = input[5] ^ 0x000005c0u;
    memory[6] = input[6] ^ 0x00000b80u;
    memory[7] = input[7] ^ 0x00001700u;
    r[0] = (r[4] < r[2]) ? r[4] + 0x10204081u : r[2] - 0x01020408u;
    /* checkpoint 1: 5a99b127; registers: 7efdfbf8 81b63110 80000000 dbdc6aeb b5851573 6df7df3e */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 1
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 6u; ++checkpoint_i0) checkpoint_result0 = (checkpoint_result0 << 5u) ^ (checkpoint_result0 >> 2u) ^ r[checkpoint_i0];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result0;
    #endif
    u32 checkpoint_memory0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 8u; ++checkpoint_i0) checkpoint_memory0 = (checkpoint_memory0 << 5u) ^ (checkpoint_memory0 >> 2u) ^ memory[checkpoint_i0];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory0;
    #endif
    return checkpoint_result0 ^ (checkpoint_memory0 << 11u | checkpoint_memory0 >> 21u);
    #endif
    #endif
    u32 shift1 = r[5] & 31u; r[5] = (shift1 == 0u ? r[2] : (r[2] << shift1) | (r[2] >> (32u - shift1))) ^ (((shift1 + 7u) & 31u) == 0u ? r[5] : (r[5] >> ((shift1 + 7u) & 31u)) | (r[5] << (32u - ((shift1 + 7u) & 31u))));
    /* checkpoint 2: e401d0e0; registers: 7efdfbf8 81b63110 80000000 dbdc6aeb b5851573 d36fbef9 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 2
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 6u; ++checkpoint_i1) checkpoint_result1 = (checkpoint_result1 << 5u) ^ (checkpoint_result1 >> 2u) ^ r[checkpoint_i1];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result1;
    #endif
    u32 checkpoint_memory1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 8u; ++checkpoint_i1) checkpoint_memory1 = (checkpoint_memory1 << 5u) ^ (checkpoint_memory1 >> 2u) ^ memory[checkpoint_i1];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory1;
    #endif
    return checkpoint_result1 ^ (checkpoint_memory1 << 11u | checkpoint_memory1 >> 21u);
    #endif
    #endif
    u32 sum2 = r[5] + r[1]; r[0] = sum2 ^ (sum2 < r[5]);
    /* checkpoint 3: 93b02484; registers: 5525f008 81b63110 80000000 dbdc6aeb b5851573 d36fbef9 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 3
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 6u; ++checkpoint_i2) checkpoint_result2 = (checkpoint_result2 << 5u) ^ (checkpoint_result2 >> 2u) ^ r[checkpoint_i2];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result2;
    #endif
    u32 checkpoint_memory2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 8u; ++checkpoint_i2) checkpoint_memory2 = (checkpoint_memory2 << 5u) ^ (checkpoint_memory2 >> 2u) ^ memory[checkpoint_i2];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory2;
    #endif
    return checkpoint_result2 ^ (checkpoint_memory2 << 11u | checkpoint_memory2 >> 21u);
    #endif
    #endif
    u32 diff3 = r[2] - r[5]; r[2] = diff3 ^ (r[2] < r[5]);
    /* checkpoint 4: eae0e384; registers: 5525f008 81b63110 ac904106 dbdc6aeb b5851573 d36fbef9 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 4
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 6u; ++checkpoint_i3) checkpoint_result3 = (checkpoint_result3 << 5u) ^ (checkpoint_result3 >> 2u) ^ r[checkpoint_i3];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result3;
    #endif
    u32 checkpoint_memory3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 8u; ++checkpoint_i3) checkpoint_memory3 = (checkpoint_memory3 << 5u) ^ (checkpoint_memory3 >> 2u) ^ memory[checkpoint_i3];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory3;
    #endif
    return checkpoint_result3 ^ (checkpoint_memory3 << 11u | checkpoint_memory3 >> 21u);
    #endif
    #endif
    r[3] = r[3] * (r[3] | 1u) + 0x9e3779b9u;
    /* checkpoint 5: 474f2ff5; registers: 5525f008 81b63110 ac904106 a0c6ed72 b5851573 d36fbef9 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 5
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 6u; ++checkpoint_i4) checkpoint_result4 = (checkpoint_result4 << 5u) ^ (checkpoint_result4 >> 2u) ^ r[checkpoint_i4];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result4;
    #endif
    u32 checkpoint_memory4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 8u; ++checkpoint_i4) checkpoint_memory4 = (checkpoint_memory4 << 5u) ^ (checkpoint_memory4 >> 2u) ^ memory[checkpoint_i4];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory4;
    #endif
    return checkpoint_result4 ^ (checkpoint_memory4 << 11u | checkpoint_memory4 >> 21u);
    #endif
    #endif
    u32 polynomial5 = r[4]; const u32 coefficient5[4] = { 3u, 5u, 17u, 257u }; for (u32 i5 = 0u; i5 < 4u; ++i5) polynomial5 = polynomial5 * (r[0] | 1u) + coefficient5[i5]; r[1] = polynomial5;
    /* checkpoint 6: 9ac12d48; registers: 5525f008 df97c40d ac904106 a0c6ed72 b5851573 d36fbef9 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 6
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 6u; ++checkpoint_i5) checkpoint_result5 = (checkpoint_result5 << 5u) ^ (checkpoint_result5 >> 2u) ^ r[checkpoint_i5];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result5;
    #endif
    u32 checkpoint_memory5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 8u; ++checkpoint_i5) checkpoint_memory5 = (checkpoint_memory5 << 5u) ^ (checkpoint_memory5 >> 2u) ^ memory[checkpoint_i5];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory5;
    #endif
    return checkpoint_result5 ^ (checkpoint_memory5 << 11u | checkpoint_memory5 >> 21u);
    #endif
    #endif
    r[0] = (r[3] < r[5]) ? r[3] + 0x10204081u : r[5] - 0x01020408u;
    /* checkpoint 7: 5ba045c9; registers: b0e72df3 df97c40d ac904106 a0c6ed72 b5851573 d36fbef9 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 7
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 6u; ++checkpoint_i6) checkpoint_result6 = (checkpoint_result6 << 5u) ^ (checkpoint_result6 >> 2u) ^ r[checkpoint_i6];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result6;
    #endif
    u32 checkpoint_memory6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 8u; ++checkpoint_i6) checkpoint_memory6 = (checkpoint_memory6 << 5u) ^ (checkpoint_memory6 >> 2u) ^ memory[checkpoint_i6];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory6;
    #endif
    return checkpoint_result6 ^ (checkpoint_memory6 << 11u | checkpoint_memory6 >> 21u);
    #endif
    #endif
    u32 low7 = r[1] + r[5], carry7 = low7 < r[1]; u32 high7 = r[2] + r[3] + carry7; r[2] = low7 ^ high7;
    /* checkpoint 8: a9ba669a; registers: b0e72df3 df97c40d fe50ad7f a0c6ed72 b5851573 d36fbef9 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 8
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 6u; ++checkpoint_i7) checkpoint_result7 = (checkpoint_result7 << 5u) ^ (checkpoint_result7 >> 2u) ^ r[checkpoint_i7];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result7;
    #endif
    u32 checkpoint_memory7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 8u; ++checkpoint_i7) checkpoint_memory7 = (checkpoint_memory7 << 5u) ^ (checkpoint_memory7 >> 2u) ^ memory[checkpoint_i7];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory7;
    #endif
    return checkpoint_result7 ^ (checkpoint_memory7 << 11u | checkpoint_memory7 >> 21u);
    #endif
    #endif
    u32 polynomial8 = r[5]; const u32 coefficient8[4] = { 3u, 5u, 17u, 257u }; for (u32 i8 = 0u; i8 < 4u; ++i8) polynomial8 = polynomial8 * (r[2] | 1u) + coefficient8[i8]; r[0] = polynomial8;
    /* checkpoint 9: 1580d057; registers: faa411eb df97c40d fe50ad7f a0c6ed72 b5851573 d36fbef9 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 9
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 6u; ++checkpoint_i8) checkpoint_result8 = (checkpoint_result8 << 5u) ^ (checkpoint_result8 >> 2u) ^ r[checkpoint_i8];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result8;
    #endif
    u32 checkpoint_memory8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 8u; ++checkpoint_i8) checkpoint_memory8 = (checkpoint_memory8 << 5u) ^ (checkpoint_memory8 >> 2u) ^ memory[checkpoint_i8];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory8;
    #endif
    return checkpoint_result8 ^ (checkpoint_memory8 << 11u | checkpoint_memory8 >> 21u);
    #endif
    #endif
    u32 diff9 = r[5] - r[1]; r[0] = diff9 ^ (r[5] < r[1]);
    /* checkpoint 10: b1bcd18d; registers: f3d7faed df97c40d fe50ad7f a0c6ed72 b5851573 d36fbef9 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 10
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 6u; ++checkpoint_i9) checkpoint_result9 = (checkpoint_result9 << 5u) ^ (checkpoint_result9 >> 2u) ^ r[checkpoint_i9];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result9;
    #endif
    u32 checkpoint_memory9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 8u; ++checkpoint_i9) checkpoint_memory9 = (checkpoint_memory9 << 5u) ^ (checkpoint_memory9 >> 2u) ^ memory[checkpoint_i9];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory9;
    #endif
    return checkpoint_result9 ^ (checkpoint_memory9 << 11u | checkpoint_memory9 >> 21u);
    #endif
    #endif
    u32 low10 = r[0] < r[1] ? r[0] : r[1], high10 = r[0] > r[1] ? r[0] : r[1]; u32 clamp10 = r[3] < low10 ? low10 : (r[3] > high10 ? high10 : r[3]); r[3] = clamp10 ^ low10 ^ high10;
    /* checkpoint 11: 70d3bcec; registers: f3d7faed df97c40d fe50ad7f f3d7faed b5851573 d36fbef9 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 11
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 6u; ++checkpoint_i10) checkpoint_result10 = (checkpoint_result10 << 5u) ^ (checkpoint_result10 >> 2u) ^ r[checkpoint_i10];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result10;
    #endif
    u32 checkpoint_memory10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 8u; ++checkpoint_i10) checkpoint_memory10 = (checkpoint_memory10 << 5u) ^ (checkpoint_memory10 >> 2u) ^ memory[checkpoint_i10];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory10;
    #endif
    return checkpoint_result10 ^ (checkpoint_memory10 << 11u | checkpoint_memory10 >> 21u);
    #endif
    #endif
    r[2] = (r[4] < r[4]) ? r[4] + 0x10204081u : r[4] - 0x01020408u;
    /* checkpoint 12: 39e99e3c; registers: f3d7faed df97c40d b483116b f3d7faed b5851573 d36fbef9 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 12
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 6u; ++checkpoint_i11) checkpoint_result11 = (checkpoint_result11 << 5u) ^ (checkpoint_result11 >> 2u) ^ r[checkpoint_i11];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result11;
    #endif
    u32 checkpoint_memory11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 8u; ++checkpoint_i11) checkpoint_memory11 = (checkpoint_memory11 << 5u) ^ (checkpoint_memory11 >> 2u) ^ memory[checkpoint_i11];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory11;
    #endif
    return checkpoint_result11 ^ (checkpoint_memory11 << 11u | checkpoint_memory11 >> 21u);
    #endif
    #endif
    /* reference final registers: f3d7faed df97c40d b483116b f3d7faed b5851573 d36fbef9 */
    /* reference final memory: e331b8e6 dfb97013 4f3581de 80000170 8a2ec17d 800005c0 12f8e442 dbdc7deb */
    u32 result = 0x9e3779b9u;
    for (u32 i = 0u; i < 6u; ++i) result = (result << 5u) ^ (result >> 2u) ^ r[i];
    u32 memory_result = 0x9e3779b9u;
    for (u32 i = 0u; i < 8u; ++i) memory_result = (memory_result << 5u) ^ (memory_result >> 2u) ^ memory[i];
    return result ^ ((memory_result << 11u) | (memory_result >> 21u));
}
#endif
