/* Generated by remu-casegen. Do not edit by hand.
* case: case_0461
* name: sparse-switch--sub-borrow-multiply-low-sub-borrow-1cd
* category: control-flow
* structural signature: sub-borrow,multiply-low,sub-borrow,sub-borrow,switch-phi,minmax-clamp,halfword-swap,horner-loop,mask-merge,rotate-mix,reverse-loop,halfword-swap
* inspiration: https://gcc.gnu.org/onlinedocs/gccint/Testsuites.html#index-gcc_002ec_002dtorture
* kernel expected: 0x996f07e5
* expected: 0xb6620ce3
* Contract: freestanding ISO C unsigned arithmetic; no undefined behavior.
*/
typedef unsigned int u32;
typedef unsigned short u16;
typedef unsigned char u8;

static volatile u32 input[16] = { 0xd14da190u, 0x63df7d13u, 0xa7ce019du, 0xf31f9122u, 0xe170d3a0u, 0x4423daebu, 0xfe9ef931u, 0x996fa675u, 0x0f547b51u, 0x0006bedeu, 0xd16cadefu, 0xffffffffu, 0x482ae890u, 0xa94ed39fu, 0x744861b7u, 0x41885837u };

__attribute__((noinline)) static u32 remu_kernel(void)
{
    u32 selector = input[0] & 0xffffu;
    switch (selector) {
    case 1u: return input[1]; case 17u: return input[2]; case 257u: return input[3];
    case 4093u: return input[4]; case 32749u: return input[5]; case 65535u: return input[6];
    default: return input[7] ^ selector;
    }
}

#ifdef REMU_KERNEL_ONLY
__attribute__((noinline, used)) u32 remu_case(void)
{
    return remu_kernel();
}
#else
__attribute__((noinline, used)) u32 remu_case(void)
{
    u32 r[6];
    u32 memory[8];
    r[0] = remu_kernel();
    r[1] = input[14];
    r[2] = input[2];
    r[3] = input[6];
    r[4] = input[10];
    r[5] = 0xe9e63225u;
    memory[0] = input[0] ^ 0x000001cdu;
    memory[1] = input[1] ^ 0x0000039au;
    memory[2] = input[2] ^ 0x00000734u;
    memory[3] = input[3] ^ 0x00000e68u;
    memory[4] = input[4] ^ 0x00001cd0u;
    memory[5] = input[5] ^ 0x000039a0u;
    memory[6] = input[6] ^ 0x00007340u;
    memory[7] = input[7] ^ 0x0000e680u;
    u32 diff0 = r[0] - r[0]; r[4] = diff0 ^ (r[0] < r[0]);
    /* checkpoint 1: 6ea89a9e; registers: 996f07e5 744861b7 a7ce019d fe9ef931 00000000 e9e63225 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 1
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 6u; ++checkpoint_i0) checkpoint_result0 = (checkpoint_result0 << 5u) ^ (checkpoint_result0 >> 2u) ^ r[checkpoint_i0];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result0;
    #endif
    u32 checkpoint_memory0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 8u; ++checkpoint_i0) checkpoint_memory0 = (checkpoint_memory0 << 5u) ^ (checkpoint_memory0 >> 2u) ^ memory[checkpoint_i0];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory0;
    #endif
    return checkpoint_result0 ^ (checkpoint_memory0 << 11u | checkpoint_memory0 >> 21u);
    #endif
    #endif
    r[5] = r[1] * (r[4] | 1u) + 0x9e3779b9u;
    /* checkpoint 2: 953173cb; registers: 996f07e5 744861b7 a7ce019d fe9ef931 00000000 127fdb70 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 2
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 6u; ++checkpoint_i1) checkpoint_result1 = (checkpoint_result1 << 5u) ^ (checkpoint_result1 >> 2u) ^ r[checkpoint_i1];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result1;
    #endif
    u32 checkpoint_memory1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 8u; ++checkpoint_i1) checkpoint_memory1 = (checkpoint_memory1 << 5u) ^ (checkpoint_memory1 >> 2u) ^ memory[checkpoint_i1];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory1;
    #endif
    return checkpoint_result1 ^ (checkpoint_memory1 << 11u | checkpoint_memory1 >> 21u);
    #endif
    #endif
    u32 diff2 = r[3] - r[5]; r[5] = diff2 ^ (r[3] < r[5]);
    /* checkpoint 3: 6b51b57a; registers: 996f07e5 744861b7 a7ce019d fe9ef931 00000000 ec1f1dc1 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 3
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 6u; ++checkpoint_i2) checkpoint_result2 = (checkpoint_result2 << 5u) ^ (checkpoint_result2 >> 2u) ^ r[checkpoint_i2];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result2;
    #endif
    u32 checkpoint_memory2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 8u; ++checkpoint_i2) checkpoint_memory2 = (checkpoint_memory2 << 5u) ^ (checkpoint_memory2 >> 2u) ^ memory[checkpoint_i2];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory2;
    #endif
    return checkpoint_result2 ^ (checkpoint_memory2 << 11u | checkpoint_memory2 >> 21u);
    #endif
    #endif
    u32 diff3 = r[4] - r[0]; r[4] = diff3 ^ (r[4] < r[0]);
    /* checkpoint 4: a0ea883c; registers: 996f07e5 744861b7 a7ce019d fe9ef931 6690f81a ec1f1dc1 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 4
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 6u; ++checkpoint_i3) checkpoint_result3 = (checkpoint_result3 << 5u) ^ (checkpoint_result3 >> 2u) ^ r[checkpoint_i3];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result3;
    #endif
    u32 checkpoint_memory3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 8u; ++checkpoint_i3) checkpoint_memory3 = (checkpoint_memory3 << 5u) ^ (checkpoint_memory3 >> 2u) ^ memory[checkpoint_i3];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory3;
    #endif
    return checkpoint_result3 ^ (checkpoint_memory3 << 11u | checkpoint_memory3 >> 21u);
    #endif
    #endif
    switch (r[3] & 3u) { case 0u: r[2] = r[1] + r[3]; break; case 1u: r[2] = r[1] - r[3]; break; case 2u: r[2] = r[1] ^ (r[3] << 5u | r[3] >> 27u); break; default: r[2] = r[1] * 3u ^ r[3]; break; }
    /* checkpoint 5: b4895fbe; registers: 996f07e5 744861b7 75a96886 fe9ef931 6690f81a ec1f1dc1 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 5
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 6u; ++checkpoint_i4) checkpoint_result4 = (checkpoint_result4 << 5u) ^ (checkpoint_result4 >> 2u) ^ r[checkpoint_i4];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result4;
    #endif
    u32 checkpoint_memory4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 8u; ++checkpoint_i4) checkpoint_memory4 = (checkpoint_memory4 << 5u) ^ (checkpoint_memory4 >> 2u) ^ memory[checkpoint_i4];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory4;
    #endif
    return checkpoint_result4 ^ (checkpoint_memory4 << 11u | checkpoint_memory4 >> 21u);
    #endif
    #endif
    u32 low5 = r[2] < r[3] ? r[2] : r[3], high5 = r[2] > r[3] ? r[2] : r[3]; u32 clamp5 = r[3] < low5 ? low5 : (r[3] > high5 ? high5 : r[3]); r[3] = clamp5 ^ low5 ^ high5;
    /* checkpoint 6: 227cfabd; registers: 996f07e5 744861b7 75a96886 75a96886 6690f81a ec1f1dc1 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 6
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 6u; ++checkpoint_i5) checkpoint_result5 = (checkpoint_result5 << 5u) ^ (checkpoint_result5 >> 2u) ^ r[checkpoint_i5];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result5;
    #endif
    u32 checkpoint_memory5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 8u; ++checkpoint_i5) checkpoint_memory5 = (checkpoint_memory5 << 5u) ^ (checkpoint_memory5 >> 2u) ^ memory[checkpoint_i5];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory5;
    #endif
    return checkpoint_result5 ^ (checkpoint_memory5 << 11u | checkpoint_memory5 >> 21u);
    #endif
    #endif
    r[2] = (r[4] << 16u | r[4] >> 16u) ^ (r[4] & 0xffff0000u);
    /* checkpoint 7: 43937ea1; registers: 996f07e5 744861b7 9e8a6690 75a96886 6690f81a ec1f1dc1 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 7
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 6u; ++checkpoint_i6) checkpoint_result6 = (checkpoint_result6 << 5u) ^ (checkpoint_result6 >> 2u) ^ r[checkpoint_i6];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result6;
    #endif
    u32 checkpoint_memory6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 8u; ++checkpoint_i6) checkpoint_memory6 = (checkpoint_memory6 << 5u) ^ (checkpoint_memory6 >> 2u) ^ memory[checkpoint_i6];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory6;
    #endif
    return checkpoint_result6 ^ (checkpoint_memory6 << 11u | checkpoint_memory6 >> 21u);
    #endif
    #endif
    u32 polynomial7 = r[1]; const u32 coefficient7[4] = { 3u, 5u, 17u, 257u }; for (u32 i7 = 0u; i7 < 4u; ++i7) polynomial7 = polynomial7 * (r[2] | 1u) + coefficient7[i7]; r[1] = polynomial7;
    /* checkpoint 8: 0591eccb; registers: 996f07e5 169b9ad1 9e8a6690 75a96886 6690f81a ec1f1dc1 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 8
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 6u; ++checkpoint_i7) checkpoint_result7 = (checkpoint_result7 << 5u) ^ (checkpoint_result7 >> 2u) ^ r[checkpoint_i7];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result7;
    #endif
    u32 checkpoint_memory7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 8u; ++checkpoint_i7) checkpoint_memory7 = (checkpoint_memory7 << 5u) ^ (checkpoint_memory7 >> 2u) ^ memory[checkpoint_i7];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory7;
    #endif
    return checkpoint_result7 ^ (checkpoint_memory7 << 11u | checkpoint_memory7 >> 21u);
    #endif
    #endif
    u32 mask8 = (r[0] << 11u) | (r[0] >> 21u); r[1] = (r[0] & mask8) | (r[0] & ~mask8);
    /* checkpoint 9: e25e194e; registers: 996f07e5 996f07e5 9e8a6690 75a96886 6690f81a ec1f1dc1 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 9
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 6u; ++checkpoint_i8) checkpoint_result8 = (checkpoint_result8 << 5u) ^ (checkpoint_result8 >> 2u) ^ r[checkpoint_i8];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result8;
    #endif
    u32 checkpoint_memory8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 8u; ++checkpoint_i8) checkpoint_memory8 = (checkpoint_memory8 << 5u) ^ (checkpoint_memory8 >> 2u) ^ memory[checkpoint_i8];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory8;
    #endif
    return checkpoint_result8 ^ (checkpoint_memory8 << 11u | checkpoint_memory8 >> 21u);
    #endif
    #endif
    u32 shift9 = r[4] & 31u; r[0] = (shift9 == 0u ? r[2] : (r[2] << shift9) | (r[2] >> (32u - shift9))) ^ (((shift9 + 7u) & 31u) == 0u ? r[4] : (r[4] >> ((shift9 + 7u) & 31u)) | (r[4] << (32u - ((shift9 + 7u) & 31u))));
    /* checkpoint 10: a7afa75c; registers: 71325597 996f07e5 9e8a6690 75a96886 6690f81a ec1f1dc1 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 10
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 6u; ++checkpoint_i9) checkpoint_result9 = (checkpoint_result9 << 5u) ^ (checkpoint_result9 >> 2u) ^ r[checkpoint_i9];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result9;
    #endif
    u32 checkpoint_memory9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 8u; ++checkpoint_i9) checkpoint_memory9 = (checkpoint_memory9 << 5u) ^ (checkpoint_memory9 >> 2u) ^ memory[checkpoint_i9];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory9;
    #endif
    return checkpoint_result9 ^ (checkpoint_memory9 << 11u | checkpoint_memory9 >> 21u);
    #endif
    #endif
    u32 source10 = r[5], reversed10 = 0u; for (u32 i10 = 0u; i10 < 32u; ++i10) { reversed10 = (reversed10 << 1u) | (source10 & 1u); source10 >>= 1u; } r[1] = reversed10 ^ r[2];
    /* checkpoint 11: e30bba44; registers: 71325597 1d329ea7 9e8a6690 75a96886 6690f81a ec1f1dc1 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 11
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 6u; ++checkpoint_i10) checkpoint_result10 = (checkpoint_result10 << 5u) ^ (checkpoint_result10 >> 2u) ^ r[checkpoint_i10];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result10;
    #endif
    u32 checkpoint_memory10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 8u; ++checkpoint_i10) checkpoint_memory10 = (checkpoint_memory10 << 5u) ^ (checkpoint_memory10 >> 2u) ^ memory[checkpoint_i10];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory10;
    #endif
    return checkpoint_result10 ^ (checkpoint_memory10 << 11u | checkpoint_memory10 >> 21u);
    #endif
    #endif
    r[1] = (r[0] << 16u | r[0] >> 16u) ^ (r[0] & 0xffff0000u);
    /* checkpoint 12: b6620ce3; registers: 71325597 24a57132 9e8a6690 75a96886 6690f81a ec1f1dc1 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 12
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 6u; ++checkpoint_i11) checkpoint_result11 = (checkpoint_result11 << 5u) ^ (checkpoint_result11 >> 2u) ^ r[checkpoint_i11];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result11;
    #endif
    u32 checkpoint_memory11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 8u; ++checkpoint_i11) checkpoint_memory11 = (checkpoint_memory11 << 5u) ^ (checkpoint_memory11 >> 2u) ^ memory[checkpoint_i11];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory11;
    #endif
    return checkpoint_result11 ^ (checkpoint_memory11 << 11u | checkpoint_memory11 >> 21u);
    #endif
    #endif
    /* reference final registers: 71325597 24a57132 9e8a6690 75a96886 6690f81a ec1f1dc1 */
    /* reference final memory: d14da05d 63df7e89 a7ce06a9 f31f9f4a e170cf70 4423e34b fe9e8a71 996f40f5 */
    u32 result = 0x9e3779b9u;
    for (u32 i = 0u; i < 6u; ++i) result = (result << 5u) ^ (result >> 2u) ^ r[i];
    u32 memory_result = 0x9e3779b9u;
    for (u32 i = 0u; i < 8u; ++i) memory_result = (memory_result << 5u) ^ (memory_result >> 2u) ^ memory[i];
    return result ^ ((memory_result << 11u) | (memory_result >> 21u));
}
#endif
