/* Generated by renvo-casegen. Do not edit by hand.
* case: case_0347
* name: byte-histogram--byte-pack-endian-swap-add-carry-15b
* category: data-layout
* structural signature: byte-pack,endian-swap,add-carry,horner-loop,minmax-clamp,endian-swap,counted-loop,switch-phi,endian-swap,horner-loop,horner-loop,array-scatter
* inspiration: https://llvm.org/docs/TestingGuide.html#test-suite-overview
* kernel expected: 0x5c754c38
* expected: 0x208d08b9
* Contract: freestanding ISO C unsigned arithmetic; no undefined behavior.
*/
typedef unsigned int u32;
typedef unsigned short u16;
typedef unsigned char u8;

static volatile u32 input[16] = { 0x1b7144a2u, 0xe3f3d078u, 0xf9f4821cu, 0xdea2a48cu, 0x8a62df6cu, 0x4ee5ffebu, 0xfffffffeu, 0x5b299408u, 0xee285608u, 0x4932ad51u, 0x00000002u, 0x378dfab5u, 0x9ef692acu, 0xb71f7e32u, 0x96aa4495u, 0xe2db3760u };

__attribute__((noinline)) static u32 renvo_kernel(void)
{
    u32 bins[8] = { 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u };
    for (u32 i = 0u; i < 14u; ++i) ++bins[(u8)input[i] & 7u];
    u32 result = 0x9e3779b9u;
    for (u32 i = 0u; i < 8u; ++i) result = (result << 5u) ^ (result >> 2u) ^ bins[i];
    return result;
}

#ifdef RENVO_KERNEL_ONLY
__attribute__((noinline, used)) u32 renvo_case(void)
{
    return renvo_kernel();
}
#else
__attribute__((noinline, used)) u32 renvo_case(void)
{
    u32 r[6];
    u32 memory[8];
    r[0] = renvo_kernel();
    r[1] = input[12];
    r[2] = input[0];
    r[3] = input[4];
    r[4] = input[8];
    r[5] = 0x7531fdc3u;
    memory[0] = input[0] ^ 0x0000015bu;
    memory[1] = input[1] ^ 0x000002b6u;
    memory[2] = input[2] ^ 0x0000056cu;
    memory[3] = input[3] ^ 0x00000ad8u;
    memory[4] = input[4] ^ 0x000015b0u;
    memory[5] = input[5] ^ 0x00002b60u;
    memory[6] = input[6] ^ 0x000056c0u;
    memory[7] = input[7] ^ 0x0000ad80u;
    r[5] = (r[2] & 0xffu) | ((r[4] & 0xffu) << 8u) | (((r[2] >> 8u) & 0xffu) << 16u) | (((r[4] >> 8u) & 0xffu) << 24u);
    /* checkpoint 1: e7a29193; registers: 5c754c38 9ef692ac 1b7144a2 8a62df6c ee285608 564408a2 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 1
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 6u; ++checkpoint_i0) checkpoint_result0 = (checkpoint_result0 << 5u) ^ (checkpoint_result0 >> 2u) ^ r[checkpoint_i0];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result0;
    #endif
    u32 checkpoint_memory0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 8u; ++checkpoint_i0) checkpoint_memory0 = (checkpoint_memory0 << 5u) ^ (checkpoint_memory0 >> 2u) ^ memory[checkpoint_i0];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory0;
    #endif
    return checkpoint_result0 ^ (checkpoint_memory0 << 11u | checkpoint_memory0 >> 21u);
    #endif
    #endif
    u32 endian1 = ((r[2] & 0xffu) << 24u) | ((r[2] & 0xff00u) << 8u) | ((r[2] >> 8u) & 0xff00u) | (r[2] >> 24u); r[5] = endian1 ^ (r[2] << 8u | r[2] >> 24u);
    /* checkpoint 2: 62e64a31; registers: 5c754c38 9ef692ac 1b7144a2 8a62df6c ee285608 d300d300 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 2
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 6u; ++checkpoint_i1) checkpoint_result1 = (checkpoint_result1 << 5u) ^ (checkpoint_result1 >> 2u) ^ r[checkpoint_i1];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result1;
    #endif
    u32 checkpoint_memory1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 8u; ++checkpoint_i1) checkpoint_memory1 = (checkpoint_memory1 << 5u) ^ (checkpoint_memory1 >> 2u) ^ memory[checkpoint_i1];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory1;
    #endif
    return checkpoint_result1 ^ (checkpoint_memory1 << 11u | checkpoint_memory1 >> 21u);
    #endif
    #endif
    u32 sum2 = r[4] + r[5]; r[4] = sum2 ^ (sum2 < r[4]);
    /* checkpoint 3: 8909f5d1; registers: 5c754c38 9ef692ac 1b7144a2 8a62df6c c1292909 d300d300 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 3
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 6u; ++checkpoint_i2) checkpoint_result2 = (checkpoint_result2 << 5u) ^ (checkpoint_result2 >> 2u) ^ r[checkpoint_i2];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result2;
    #endif
    u32 checkpoint_memory2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 8u; ++checkpoint_i2) checkpoint_memory2 = (checkpoint_memory2 << 5u) ^ (checkpoint_memory2 >> 2u) ^ memory[checkpoint_i2];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory2;
    #endif
    return checkpoint_result2 ^ (checkpoint_memory2 << 11u | checkpoint_memory2 >> 21u);
    #endif
    #endif
    u32 polynomial3 = r[0]; const u32 coefficient3[4] = { 3u, 5u, 17u, 257u }; for (u32 i3 = 0u; i3 < 4u; ++i3) polynomial3 = polynomial3 * (r[2] | 1u) + coefficient3[i3]; r[3] = polynomial3;
    /* checkpoint 4: c6daff01; registers: 5c754c38 9ef692ac 1b7144a2 3c53f36a c1292909 d300d300 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 4
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 6u; ++checkpoint_i3) checkpoint_result3 = (checkpoint_result3 << 5u) ^ (checkpoint_result3 >> 2u) ^ r[checkpoint_i3];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result3;
    #endif
    u32 checkpoint_memory3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 8u; ++checkpoint_i3) checkpoint_memory3 = (checkpoint_memory3 << 5u) ^ (checkpoint_memory3 >> 2u) ^ memory[checkpoint_i3];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory3;
    #endif
    return checkpoint_result3 ^ (checkpoint_memory3 << 11u | checkpoint_memory3 >> 21u);
    #endif
    #endif
    u32 low4 = r[0] < r[3] ? r[0] : r[3], high4 = r[0] > r[3] ? r[0] : r[3]; u32 clamp4 = r[5] < low4 ? low4 : (r[5] > high4 ? high4 : r[5]); r[5] = clamp4 ^ low4 ^ high4;
    /* checkpoint 5: 2989df6b; registers: 5c754c38 9ef692ac 1b7144a2 3c53f36a c1292909 3c53f36a */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 5
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 6u; ++checkpoint_i4) checkpoint_result4 = (checkpoint_result4 << 5u) ^ (checkpoint_result4 >> 2u) ^ r[checkpoint_i4];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result4;
    #endif
    u32 checkpoint_memory4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 8u; ++checkpoint_i4) checkpoint_memory4 = (checkpoint_memory4 << 5u) ^ (checkpoint_memory4 >> 2u) ^ memory[checkpoint_i4];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory4;
    #endif
    return checkpoint_result4 ^ (checkpoint_memory4 << 11u | checkpoint_memory4 >> 21u);
    #endif
    #endif
    u32 endian5 = ((r[2] & 0xffu) << 24u) | ((r[2] & 0xff00u) << 8u) | ((r[2] >> 8u) & 0xff00u) | (r[2] >> 24u); r[3] = endian5 ^ (r[3] << 8u | r[3] >> 24u);
    /* checkpoint 6: f6f6a5e7; registers: 5c754c38 9ef692ac 1b7144a2 f1b71b27 c1292909 3c53f36a */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 6
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 6u; ++checkpoint_i5) checkpoint_result5 = (checkpoint_result5 << 5u) ^ (checkpoint_result5 >> 2u) ^ r[checkpoint_i5];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result5;
    #endif
    u32 checkpoint_memory5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 8u; ++checkpoint_i5) checkpoint_memory5 = (checkpoint_memory5 << 5u) ^ (checkpoint_memory5 >> 2u) ^ memory[checkpoint_i5];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory5;
    #endif
    return checkpoint_result5 ^ (checkpoint_memory5 << 11u | checkpoint_memory5 >> 21u);
    #endif
    #endif
    u32 loop6 = r[0]; for (u32 i6 = 0u; i6 < 4u; ++i6) { loop6 += r[2] ^ i6; loop6 = loop6 << 3u | loop6 >> 29u; } r[2] = loop6;
    /* checkpoint 7: 4addb0d8; registers: 5c754c38 9ef692ac 03723ac5 f1b71b27 c1292909 3c53f36a */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 7
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 6u; ++checkpoint_i6) checkpoint_result6 = (checkpoint_result6 << 5u) ^ (checkpoint_result6 >> 2u) ^ r[checkpoint_i6];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result6;
    #endif
    u32 checkpoint_memory6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 8u; ++checkpoint_i6) checkpoint_memory6 = (checkpoint_memory6 << 5u) ^ (checkpoint_memory6 >> 2u) ^ memory[checkpoint_i6];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory6;
    #endif
    return checkpoint_result6 ^ (checkpoint_memory6 << 11u | checkpoint_memory6 >> 21u);
    #endif
    #endif
    switch (r[5] & 3u) { case 0u: r[5] = r[2] + r[5]; break; case 1u: r[5] = r[2] - r[5]; break; case 2u: r[5] = r[2] ^ (r[5] << 5u | r[5] >> 27u); break; default: r[5] = r[2] * 3u ^ r[5]; break; }
    /* checkpoint 8: ff821430; registers: 5c754c38 9ef692ac 03723ac5 f1b71b27 c1292909 890c5782 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 8
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 6u; ++checkpoint_i7) checkpoint_result7 = (checkpoint_result7 << 5u) ^ (checkpoint_result7 >> 2u) ^ r[checkpoint_i7];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result7;
    #endif
    u32 checkpoint_memory7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 8u; ++checkpoint_i7) checkpoint_memory7 = (checkpoint_memory7 << 5u) ^ (checkpoint_memory7 >> 2u) ^ memory[checkpoint_i7];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory7;
    #endif
    return checkpoint_result7 ^ (checkpoint_memory7 << 11u | checkpoint_memory7 >> 21u);
    #endif
    #endif
    u32 endian8 = ((r[0] & 0xffu) << 24u) | ((r[0] & 0xff00u) << 8u) | ((r[0] >> 8u) & 0xff00u) | (r[0] >> 24u); r[2] = endian8 ^ (r[1] << 8u | r[1] >> 24u);
    /* checkpoint 9: 2a8de5ba; registers: 5c754c38 9ef692ac ceded9c2 f1b71b27 c1292909 890c5782 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 9
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 6u; ++checkpoint_i8) checkpoint_result8 = (checkpoint_result8 << 5u) ^ (checkpoint_result8 >> 2u) ^ r[checkpoint_i8];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result8;
    #endif
    u32 checkpoint_memory8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 8u; ++checkpoint_i8) checkpoint_memory8 = (checkpoint_memory8 << 5u) ^ (checkpoint_memory8 >> 2u) ^ memory[checkpoint_i8];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory8;
    #endif
    return checkpoint_result8 ^ (checkpoint_memory8 << 11u | checkpoint_memory8 >> 21u);
    #endif
    #endif
    u32 polynomial9 = r[1]; const u32 coefficient9[4] = { 3u, 5u, 17u, 257u }; for (u32 i9 = 0u; i9 < 4u; ++i9) polynomial9 = polynomial9 * (r[4] | 1u) + coefficient9[i9]; r[5] = polynomial9;
    /* checkpoint 10: 38ca1bde; registers: 5c754c38 9ef692ac ceded9c2 f1b71b27 c1292909 9b4ba9e6 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 10
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 6u; ++checkpoint_i9) checkpoint_result9 = (checkpoint_result9 << 5u) ^ (checkpoint_result9 >> 2u) ^ r[checkpoint_i9];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result9;
    #endif
    u32 checkpoint_memory9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 8u; ++checkpoint_i9) checkpoint_memory9 = (checkpoint_memory9 << 5u) ^ (checkpoint_memory9 >> 2u) ^ memory[checkpoint_i9];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory9;
    #endif
    return checkpoint_result9 ^ (checkpoint_memory9 << 11u | checkpoint_memory9 >> 21u);
    #endif
    #endif
    u32 polynomial10 = r[5]; const u32 coefficient10[4] = { 3u, 5u, 17u, 257u }; for (u32 i10 = 0u; i10 < 4u; ++i10) polynomial10 = polynomial10 * (r[1] | 1u) + coefficient10[i10]; r[5] = polynomial10;
    /* checkpoint 11: d7637388; registers: 5c754c38 9ef692ac ceded9c2 f1b71b27 c1292909 74e2c1b0 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 11
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 6u; ++checkpoint_i10) checkpoint_result10 = (checkpoint_result10 << 5u) ^ (checkpoint_result10 >> 2u) ^ r[checkpoint_i10];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result10;
    #endif
    u32 checkpoint_memory10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 8u; ++checkpoint_i10) checkpoint_memory10 = (checkpoint_memory10 << 5u) ^ (checkpoint_memory10 >> 2u) ^ memory[checkpoint_i10];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory10;
    #endif
    return checkpoint_result10 ^ (checkpoint_memory10 << 11u | checkpoint_memory10 >> 21u);
    #endif
    #endif
    u32 index11 = r[5] & 7u; memory[index11] ^= r[5]; r[0] = (memory[index11] << 12u) | (memory[index11] >> 20u);
    /* checkpoint 12: 208d08b9; registers: 384496f9 9ef692ac ceded9c2 f1b71b27 c1292909 74e2c1b0 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 12
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 6u; ++checkpoint_i11) checkpoint_result11 = (checkpoint_result11 << 5u) ^ (checkpoint_result11 >> 2u) ^ r[checkpoint_i11];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result11;
    #endif
    u32 checkpoint_memory11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 8u; ++checkpoint_i11) checkpoint_memory11 = (checkpoint_memory11 << 5u) ^ (checkpoint_memory11 >> 2u) ^ memory[checkpoint_i11];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory11;
    #endif
    return checkpoint_result11 ^ (checkpoint_memory11 << 11u | checkpoint_memory11 >> 21u);
    #endif
    #endif
    /* reference final registers: 384496f9 9ef692ac ceded9c2 f1b71b27 c1292909 74e2c1b0 */
    /* reference final memory: 6f938449 e3f3d2ce f9f48770 dea2ae54 8a62cadc 4ee5d48b ffffa93e 5b293988 */
    u32 result = 0x9e3779b9u;
    for (u32 i = 0u; i < 6u; ++i) result = (result << 5u) ^ (result >> 2u) ^ r[i];
    u32 memory_result = 0x9e3779b9u;
    for (u32 i = 0u; i < 8u; ++i) memory_result = (memory_result << 5u) ^ (memory_result >> 2u) ^ memory[i];
    return result ^ ((memory_result << 11u) | (memory_result >> 21u));
}
#endif
