/* Generated by renvo-casegen. Do not edit by hand.
* case: case_0651
* name: recursive-gcd--switch-phi-short-circuit-sub-borrow-28b
* category: abi-calls
* structural signature: switch-phi,short-circuit,sub-borrow,mask-merge,mask-merge,compare-select,add-carry,sub-borrow,mask-merge,rotate-mix,popcount-loop,compare-select
* inspiration: https://gcc.gnu.org/onlinedocs/gccint/Testsuites.html#index-gcc_002ec_002dtorture
* kernel expected: 0x00000001
* expected: 0xb757406b
* Contract: freestanding ISO C unsigned arithmetic; no undefined behavior.
*/
typedef unsigned int u32;
typedef unsigned short u16;
typedef unsigned char u8;

static volatile u32 input[16] = { 0xf4a5b380u, 0x00000001u, 0xaac3f71bu, 0x17d58bfeu, 0x695ac81eu, 0xfcd17d6fu, 0x89631f11u, 0x904c3feeu, 0xc6eaaa63u, 0x5add0137u, 0x8b046a16u, 0x4e5d2e5au, 0x0f0e93b8u, 0x88a9d05eu, 0xde79a2c7u, 0x72c24310u };
__attribute__((noinline)) static u32 gcd(u32 a, u32 b)
{
    return (b == 0u) ? a : gcd(b, a % b);
}

__attribute__((noinline)) static u32 renvo_kernel(void)
{
    return gcd(20097u, 2u);
}

#ifdef RENVO_KERNEL_ONLY
__attribute__((noinline, used)) u32 renvo_case(void)
{
    return renvo_kernel();
}
#else
__attribute__((noinline, used)) u32 renvo_case(void)
{
    u32 r[6];
    u32 memory[8];
    r[0] = renvo_kernel();
    r[1] = input[12];
    r[2] = input[0];
    r[3] = input[4];
    r[4] = input[8];
    r[5] = 0x57128973u;
    memory[0] = input[0] ^ 0x0000028bu;
    memory[1] = input[1] ^ 0x00000516u;
    memory[2] = input[2] ^ 0x00000a2cu;
    memory[3] = input[3] ^ 0x00001458u;
    memory[4] = input[4] ^ 0x000028b0u;
    memory[5] = input[5] ^ 0x00005160u;
    memory[6] = input[6] ^ 0x0000a2c0u;
    memory[7] = input[7] ^ 0x00014580u;
    switch (r[5] & 3u) { case 0u: r[3] = r[1] + r[5]; break; case 1u: r[3] = r[1] - r[5]; break; case 2u: r[3] = r[1] ^ (r[5] << 5u | r[5] >> 27u); break; default: r[3] = r[1] * 3u ^ r[5]; break; }
    /* checkpoint 1: 4e82b18a; registers: 00000001 0f0e93b8 f4a5b380 7a39325b c6eaaa63 57128973 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 1
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 6u; ++checkpoint_i0) checkpoint_result0 = (checkpoint_result0 << 5u) ^ (checkpoint_result0 >> 2u) ^ r[checkpoint_i0];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result0;
    #endif
    u32 checkpoint_memory0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 8u; ++checkpoint_i0) checkpoint_memory0 = (checkpoint_memory0 << 5u) ^ (checkpoint_memory0 >> 2u) ^ memory[checkpoint_i0];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory0;
    #endif
    return checkpoint_result0 ^ (checkpoint_memory0 << 11u | checkpoint_memory0 >> 21u);
    #endif
    #endif
    u32 effects1 = r[0]; if ((r[4] & 1u) != 0u && (effects1 += 3u, (r[4] & 2u) != 0u)) effects1 ^= 0x55aa55aau; r[5] = effects1;
    /* checkpoint 2: 4c3a6d57; registers: 00000001 0f0e93b8 f4a5b380 7a39325b c6eaaa63 55aa55ae */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 2
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 6u; ++checkpoint_i1) checkpoint_result1 = (checkpoint_result1 << 5u) ^ (checkpoint_result1 >> 2u) ^ r[checkpoint_i1];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result1;
    #endif
    u32 checkpoint_memory1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 8u; ++checkpoint_i1) checkpoint_memory1 = (checkpoint_memory1 << 5u) ^ (checkpoint_memory1 >> 2u) ^ memory[checkpoint_i1];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory1;
    #endif
    return checkpoint_result1 ^ (checkpoint_memory1 << 11u | checkpoint_memory1 >> 21u);
    #endif
    #endif
    u32 diff2 = r[2] - r[0]; r[2] = diff2 ^ (r[2] < r[0]);
    /* checkpoint 3: 4c4510b2; registers: 00000001 0f0e93b8 f4a5b37f 7a39325b c6eaaa63 55aa55ae */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 3
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 6u; ++checkpoint_i2) checkpoint_result2 = (checkpoint_result2 << 5u) ^ (checkpoint_result2 >> 2u) ^ r[checkpoint_i2];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result2;
    #endif
    u32 checkpoint_memory2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 8u; ++checkpoint_i2) checkpoint_memory2 = (checkpoint_memory2 << 5u) ^ (checkpoint_memory2 >> 2u) ^ memory[checkpoint_i2];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory2;
    #endif
    return checkpoint_result2 ^ (checkpoint_memory2 << 11u | checkpoint_memory2 >> 21u);
    #endif
    #endif
    u32 mask3 = (r[2] << 6u) | (r[2] >> 26u); r[5] = (r[2] & mask3) | (r[0] & ~mask3);
    /* checkpoint 4: 39cbd661; registers: 00000001 0f0e93b8 f4a5b37f 7a39325b c6eaaa63 2024937d */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 4
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 6u; ++checkpoint_i3) checkpoint_result3 = (checkpoint_result3 << 5u) ^ (checkpoint_result3 >> 2u) ^ r[checkpoint_i3];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result3;
    #endif
    u32 checkpoint_memory3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 8u; ++checkpoint_i3) checkpoint_memory3 = (checkpoint_memory3 << 5u) ^ (checkpoint_memory3 >> 2u) ^ memory[checkpoint_i3];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory3;
    #endif
    return checkpoint_result3 ^ (checkpoint_memory3 << 11u | checkpoint_memory3 >> 21u);
    #endif
    #endif
    u32 mask4 = (r[1] << 7u) | (r[1] >> 25u); r[2] = (r[1] & mask4) | (r[4] & ~mask4);
    /* checkpoint 5: f2977443; registers: 00000001 0f0e93b8 47aab260 7a39325b c6eaaa63 2024937d */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 5
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 6u; ++checkpoint_i4) checkpoint_result4 = (checkpoint_result4 << 5u) ^ (checkpoint_result4 >> 2u) ^ r[checkpoint_i4];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result4;
    #endif
    u32 checkpoint_memory4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 8u; ++checkpoint_i4) checkpoint_memory4 = (checkpoint_memory4 << 5u) ^ (checkpoint_memory4 >> 2u) ^ memory[checkpoint_i4];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory4;
    #endif
    return checkpoint_result4 ^ (checkpoint_memory4 << 11u | checkpoint_memory4 >> 21u);
    #endif
    #endif
    r[2] = (r[2] < r[0]) ? r[2] + 0x10204081u : r[0] - 0x01020408u;
    /* checkpoint 6: 0159a247; registers: 00000001 0f0e93b8 fefdfbf9 7a39325b c6eaaa63 2024937d */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 6
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 6u; ++checkpoint_i5) checkpoint_result5 = (checkpoint_result5 << 5u) ^ (checkpoint_result5 >> 2u) ^ r[checkpoint_i5];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result5;
    #endif
    u32 checkpoint_memory5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 8u; ++checkpoint_i5) checkpoint_memory5 = (checkpoint_memory5 << 5u) ^ (checkpoint_memory5 >> 2u) ^ memory[checkpoint_i5];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory5;
    #endif
    return checkpoint_result5 ^ (checkpoint_memory5 << 11u | checkpoint_memory5 >> 21u);
    #endif
    #endif
    u32 sum6 = r[3] + r[4]; r[2] = sum6 ^ (sum6 < r[3]);
    /* checkpoint 7: 419ed05e; registers: 00000001 0f0e93b8 4123dcbf 7a39325b c6eaaa63 2024937d */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 7
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 6u; ++checkpoint_i6) checkpoint_result6 = (checkpoint_result6 << 5u) ^ (checkpoint_result6 >> 2u) ^ r[checkpoint_i6];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result6;
    #endif
    u32 checkpoint_memory6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 8u; ++checkpoint_i6) checkpoint_memory6 = (checkpoint_memory6 << 5u) ^ (checkpoint_memory6 >> 2u) ^ memory[checkpoint_i6];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory6;
    #endif
    return checkpoint_result6 ^ (checkpoint_memory6 << 11u | checkpoint_memory6 >> 21u);
    #endif
    #endif
    u32 diff7 = r[1] - r[1]; r[3] = diff7 ^ (r[1] < r[1]);
    /* checkpoint 8: 62f42f63; registers: 00000001 0f0e93b8 4123dcbf 00000000 c6eaaa63 2024937d */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 8
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 6u; ++checkpoint_i7) checkpoint_result7 = (checkpoint_result7 << 5u) ^ (checkpoint_result7 >> 2u) ^ r[checkpoint_i7];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result7;
    #endif
    u32 checkpoint_memory7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 8u; ++checkpoint_i7) checkpoint_memory7 = (checkpoint_memory7 << 5u) ^ (checkpoint_memory7 >> 2u) ^ memory[checkpoint_i7];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory7;
    #endif
    return checkpoint_result7 ^ (checkpoint_memory7 << 11u | checkpoint_memory7 >> 21u);
    #endif
    #endif
    u32 mask8 = (r[3] << 11u) | (r[3] >> 21u); r[2] = (r[3] & mask8) | (r[5] & ~mask8);
    /* checkpoint 9: 01d06dd8; registers: 00000001 0f0e93b8 2024937d 00000000 c6eaaa63 2024937d */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 9
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 6u; ++checkpoint_i8) checkpoint_result8 = (checkpoint_result8 << 5u) ^ (checkpoint_result8 >> 2u) ^ r[checkpoint_i8];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result8;
    #endif
    u32 checkpoint_memory8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 8u; ++checkpoint_i8) checkpoint_memory8 = (checkpoint_memory8 << 5u) ^ (checkpoint_memory8 >> 2u) ^ memory[checkpoint_i8];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory8;
    #endif
    return checkpoint_result8 ^ (checkpoint_memory8 << 11u | checkpoint_memory8 >> 21u);
    #endif
    #endif
    u32 shift9 = r[4] & 31u; r[5] = (shift9 == 0u ? r[2] : (r[2] << shift9) | (r[2] >> (32u - shift9))) ^ (((shift9 + 7u) & 31u) == 0u ? r[4] : (r[4] >> ((shift9 + 7u) & 31u)) | (r[4] << (32u - ((shift9 + 7u) & 31u))));
    /* checkpoint 10: b821dfe6; registers: 00000001 0f0e93b8 2024937d 00000000 c6eaaa63 99d52143 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 10
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 6u; ++checkpoint_i9) checkpoint_result9 = (checkpoint_result9 << 5u) ^ (checkpoint_result9 >> 2u) ^ r[checkpoint_i9];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result9;
    #endif
    u32 checkpoint_memory9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 8u; ++checkpoint_i9) checkpoint_memory9 = (checkpoint_memory9 << 5u) ^ (checkpoint_memory9 >> 2u) ^ memory[checkpoint_i9];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory9;
    #endif
    return checkpoint_result9 ^ (checkpoint_memory9 << 11u | checkpoint_memory9 >> 21u);
    #endif
    #endif
    u32 bits10 = r[2], count10 = 0u; while (bits10 != 0u) { bits10 &= bits10 - 1u; ++count10; } r[3] = count10 ^ r[3];
    /* checkpoint 11: b821ebee; registers: 00000001 0f0e93b8 2024937d 0000000d c6eaaa63 99d52143 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 11
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 6u; ++checkpoint_i10) checkpoint_result10 = (checkpoint_result10 << 5u) ^ (checkpoint_result10 >> 2u) ^ r[checkpoint_i10];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result10;
    #endif
    u32 checkpoint_memory10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 8u; ++checkpoint_i10) checkpoint_memory10 = (checkpoint_memory10 << 5u) ^ (checkpoint_memory10 >> 2u) ^ memory[checkpoint_i10];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory10;
    #endif
    return checkpoint_result10 ^ (checkpoint_memory10 << 11u | checkpoint_memory10 >> 21u);
    #endif
    #endif
    r[4] = (r[2] < r[2]) ? r[2] + 0x10204081u : r[2] - 0x01020408u;
    /* checkpoint 12: b757406b; registers: 00000001 0f0e93b8 2024937d 0000000d 1f228f75 99d52143 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 12
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 6u; ++checkpoint_i11) checkpoint_result11 = (checkpoint_result11 << 5u) ^ (checkpoint_result11 >> 2u) ^ r[checkpoint_i11];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result11;
    #endif
    u32 checkpoint_memory11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 8u; ++checkpoint_i11) checkpoint_memory11 = (checkpoint_memory11 << 5u) ^ (checkpoint_memory11 >> 2u) ^ memory[checkpoint_i11];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory11;
    #endif
    return checkpoint_result11 ^ (checkpoint_memory11 << 11u | checkpoint_memory11 >> 21u);
    #endif
    #endif
    /* reference final registers: 00000001 0f0e93b8 2024937d 0000000d 1f228f75 99d52143 */
    /* reference final memory: f4a5b10b 00000517 aac3fd37 17d59fa6 695ae0ae fcd12c0f 8963bdd1 904d7a6e */
    u32 result = 0x9e3779b9u;
    for (u32 i = 0u; i < 6u; ++i) result = (result << 5u) ^ (result >> 2u) ^ r[i];
    u32 memory_result = 0x9e3779b9u;
    for (u32 i = 0u; i < 8u; ++i) memory_result = (memory_result << 5u) ^ (memory_result >> 2u) ^ memory[i];
    return result ^ ((memory_result << 11u) | (memory_result >> 21u));
}
#endif
