/* Generated by renvo-casegen. Do not edit by hand.
* case: case_0264
* name: insertion-sort--divide-rem-popcount-loop-add-carry-108
* category: algorithms
* structural signature: divide-rem,popcount-loop,add-carry,minmax-clamp,byte-pack,multiply-low,rotate-mix,minmax-clamp,reverse-loop,short-circuit,multiply-low,sub-borrow
* inspiration: https://github.com/embench/embench-iot
* kernel expected: 0x043af392
* expected: 0xfca4f2ed
* Contract: freestanding ISO C unsigned arithmetic; no undefined behavior.
*/
typedef unsigned int u32;
typedef unsigned short u16;
typedef unsigned char u8;

static volatile u32 input[16] = { 0xf25d3025u, 0x07e22a2bu, 0xfffffffeu, 0x8f4e1c2cu, 0xaec3b8a3u, 0x68447b34u, 0x7b9a4f33u, 0xe14be4b4u, 0x8d6e5914u, 0x5588983cu, 0x39be2929u, 0x7f5db4e8u, 0x5c77f9b8u, 0x78c7ceacu, 0x00000002u, 0xbfd66652u };

__attribute__((noinline)) static u32 renvo_kernel(void)
{
    u32 a[16];
    for (u32 i = 0u; i < 6u; ++i) a[i] = input[i];
    for (u32 i = 1u; i < 6u; ++i) {
        u32 value = a[i], j = i;
        while (j != 0u && a[j - 1u] > value) { a[j] = a[j - 1u]; --j; }
        a[j] = value;
    }
    u32 result = 0x9e3779b9u;
    for (u32 i = 0u; i < 6u; ++i) result = (result << 5u) ^ (result >> 2u) ^ a[i];
    return result;
}

#ifdef RENVO_KERNEL_ONLY
__attribute__((noinline, used)) u32 renvo_case(void)
{
    return renvo_kernel();
}
#else
__attribute__((noinline, used)) u32 renvo_case(void)
{
    u32 r[6];
    u32 memory[8];
    r[0] = renvo_kernel();
    r[1] = input[9];
    r[2] = input[13];
    r[3] = input[1];
    r[4] = input[5];
    r[5] = 0x293586c8u;
    memory[0] = input[0] ^ 0x00000108u;
    memory[1] = input[1] ^ 0x00000210u;
    memory[2] = input[2] ^ 0x00000420u;
    memory[3] = input[3] ^ 0x00000840u;
    memory[4] = input[4] ^ 0x00001080u;
    memory[5] = input[5] ^ 0x00002100u;
    memory[6] = input[6] ^ 0x00004200u;
    memory[7] = input[7] ^ 0x00008400u;
    u32 divisor0 = (r[1] & 0xffffu) | 1u; u32 rem0 = r[2] % divisor0; r[4] = (r[2] / divisor0) ^ (rem0 << 9u | rem0 >> 23u);
    /* checkpoint 1: fd733785; registers: 043af392 5588983c 78c7ceac 07e22a2b 0123a519 293586c8 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 1
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 6u; ++checkpoint_i0) checkpoint_result0 = (checkpoint_result0 << 5u) ^ (checkpoint_result0 >> 2u) ^ r[checkpoint_i0];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result0;
    #endif
    u32 checkpoint_memory0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 8u; ++checkpoint_i0) checkpoint_memory0 = (checkpoint_memory0 << 5u) ^ (checkpoint_memory0 >> 2u) ^ memory[checkpoint_i0];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory0;
    #endif
    return checkpoint_result0 ^ (checkpoint_memory0 << 11u | checkpoint_memory0 >> 21u);
    #endif
    #endif
    u32 bits1 = r[0], count1 = 0u; while (bits1 != 0u) { bits1 &= bits1 - 1u; ++count1; } r[1] = count1 ^ r[4];
    /* checkpoint 2: 4797fe69; registers: 043af392 0123a517 78c7ceac 07e22a2b 0123a519 293586c8 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 2
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 6u; ++checkpoint_i1) checkpoint_result1 = (checkpoint_result1 << 5u) ^ (checkpoint_result1 >> 2u) ^ r[checkpoint_i1];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result1;
    #endif
    u32 checkpoint_memory1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 8u; ++checkpoint_i1) checkpoint_memory1 = (checkpoint_memory1 << 5u) ^ (checkpoint_memory1 >> 2u) ^ memory[checkpoint_i1];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory1;
    #endif
    return checkpoint_result1 ^ (checkpoint_memory1 << 11u | checkpoint_memory1 >> 21u);
    #endif
    #endif
    u32 sum2 = r[3] + r[0]; r[0] = sum2 ^ (sum2 < r[3]);
    /* checkpoint 3: 91216886; registers: 0c1d1dbd 0123a517 78c7ceac 07e22a2b 0123a519 293586c8 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 3
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 6u; ++checkpoint_i2) checkpoint_result2 = (checkpoint_result2 << 5u) ^ (checkpoint_result2 >> 2u) ^ r[checkpoint_i2];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result2;
    #endif
    u32 checkpoint_memory2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 8u; ++checkpoint_i2) checkpoint_memory2 = (checkpoint_memory2 << 5u) ^ (checkpoint_memory2 >> 2u) ^ memory[checkpoint_i2];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory2;
    #endif
    return checkpoint_result2 ^ (checkpoint_memory2 << 11u | checkpoint_memory2 >> 21u);
    #endif
    #endif
    u32 low3 = r[2] < r[1] ? r[2] : r[1], high3 = r[2] > r[1] ? r[2] : r[1]; u32 clamp3 = r[1] < low3 ? low3 : (r[1] > high3 ? high3 : r[1]); r[1] = clamp3 ^ low3 ^ high3;
    /* checkpoint 4: d6e8ee34; registers: 0c1d1dbd 78c7ceac 78c7ceac 07e22a2b 0123a519 293586c8 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 4
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 6u; ++checkpoint_i3) checkpoint_result3 = (checkpoint_result3 << 5u) ^ (checkpoint_result3 >> 2u) ^ r[checkpoint_i3];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result3;
    #endif
    u32 checkpoint_memory3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 8u; ++checkpoint_i3) checkpoint_memory3 = (checkpoint_memory3 << 5u) ^ (checkpoint_memory3 >> 2u) ^ memory[checkpoint_i3];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory3;
    #endif
    return checkpoint_result3 ^ (checkpoint_memory3 << 11u | checkpoint_memory3 >> 21u);
    #endif
    #endif
    r[0] = (r[4] & 0xffu) | ((r[5] & 0xffu) << 8u) | (((r[4] >> 8u) & 0xffu) << 16u) | (((r[5] >> 8u) & 0xffu) << 24u);
    /* checkpoint 5: 200d78e5; registers: 86a5c819 78c7ceac 78c7ceac 07e22a2b 0123a519 293586c8 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 5
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 6u; ++checkpoint_i4) checkpoint_result4 = (checkpoint_result4 << 5u) ^ (checkpoint_result4 >> 2u) ^ r[checkpoint_i4];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result4;
    #endif
    u32 checkpoint_memory4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 8u; ++checkpoint_i4) checkpoint_memory4 = (checkpoint_memory4 << 5u) ^ (checkpoint_memory4 >> 2u) ^ memory[checkpoint_i4];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory4;
    #endif
    return checkpoint_result4 ^ (checkpoint_memory4 << 11u | checkpoint_memory4 >> 21u);
    #endif
    #endif
    r[2] = r[3] * (r[1] | 1u) + 0x9e3779b9u;
    /* checkpoint 6: 6da11d54; registers: 86a5c819 78c7ceac df6992c8 07e22a2b 0123a519 293586c8 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 6
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 6u; ++checkpoint_i5) checkpoint_result5 = (checkpoint_result5 << 5u) ^ (checkpoint_result5 >> 2u) ^ r[checkpoint_i5];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result5;
    #endif
    u32 checkpoint_memory5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 8u; ++checkpoint_i5) checkpoint_memory5 = (checkpoint_memory5 << 5u) ^ (checkpoint_memory5 >> 2u) ^ memory[checkpoint_i5];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory5;
    #endif
    return checkpoint_result5 ^ (checkpoint_memory5 << 11u | checkpoint_memory5 >> 21u);
    #endif
    #endif
    u32 shift6 = r[0] & 31u; r[2] = (shift6 == 0u ? r[1] : (r[1] << shift6) | (r[1] >> (32u - shift6))) ^ (((shift6 + 7u) & 31u) == 0u ? r[0] : (r[0] >> ((shift6 + 7u) & 31u)) | (r[0] << (32u - ((shift6 + 7u) & 31u))));
    /* checkpoint 7: b8ad0c81; registers: 86a5c819 78c7ceac de544784 07e22a2b 0123a519 293586c8 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 7
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 6u; ++checkpoint_i6) checkpoint_result6 = (checkpoint_result6 << 5u) ^ (checkpoint_result6 >> 2u) ^ r[checkpoint_i6];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result6;
    #endif
    u32 checkpoint_memory6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 8u; ++checkpoint_i6) checkpoint_memory6 = (checkpoint_memory6 << 5u) ^ (checkpoint_memory6 >> 2u) ^ memory[checkpoint_i6];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory6;
    #endif
    return checkpoint_result6 ^ (checkpoint_memory6 << 11u | checkpoint_memory6 >> 21u);
    #endif
    #endif
    u32 low7 = r[2] < r[1] ? r[2] : r[1], high7 = r[2] > r[1] ? r[2] : r[1]; u32 clamp7 = r[2] < low7 ? low7 : (r[2] > high7 ? high7 : r[2]); r[2] = clamp7 ^ low7 ^ high7;
    /* checkpoint 8: 200d78e5; registers: 86a5c819 78c7ceac 78c7ceac 07e22a2b 0123a519 293586c8 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 8
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 6u; ++checkpoint_i7) checkpoint_result7 = (checkpoint_result7 << 5u) ^ (checkpoint_result7 >> 2u) ^ r[checkpoint_i7];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result7;
    #endif
    u32 checkpoint_memory7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 8u; ++checkpoint_i7) checkpoint_memory7 = (checkpoint_memory7 << 5u) ^ (checkpoint_memory7 >> 2u) ^ memory[checkpoint_i7];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory7;
    #endif
    return checkpoint_result7 ^ (checkpoint_memory7 << 11u | checkpoint_memory7 >> 21u);
    #endif
    #endif
    u32 source8 = r[1], reversed8 = 0u; for (u32 i8 = 0u; i8 < 32u; ++i8) { reversed8 = (reversed8 << 1u) | (source8 & 1u); source8 >>= 1u; } r[2] = reversed8 ^ r[1];
    /* checkpoint 9: a8536d4d; registers: 86a5c819 78c7ceac 4db42db2 07e22a2b 0123a519 293586c8 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 9
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 6u; ++checkpoint_i8) checkpoint_result8 = (checkpoint_result8 << 5u) ^ (checkpoint_result8 >> 2u) ^ r[checkpoint_i8];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result8;
    #endif
    u32 checkpoint_memory8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 8u; ++checkpoint_i8) checkpoint_memory8 = (checkpoint_memory8 << 5u) ^ (checkpoint_memory8 >> 2u) ^ memory[checkpoint_i8];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory8;
    #endif
    return checkpoint_result8 ^ (checkpoint_memory8 << 11u | checkpoint_memory8 >> 21u);
    #endif
    #endif
    u32 effects9 = r[3]; if ((r[1] & 1u) != 0u && (effects9 += 3u, (r[1] & 2u) != 0u)) effects9 ^= 0x55aa55aau; r[4] = effects9;
    /* checkpoint 10: 71d2e8c1; registers: 86a5c819 78c7ceac 4db42db2 07e22a2b 07e22a2b 293586c8 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 10
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 6u; ++checkpoint_i9) checkpoint_result9 = (checkpoint_result9 << 5u) ^ (checkpoint_result9 >> 2u) ^ r[checkpoint_i9];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result9;
    #endif
    u32 checkpoint_memory9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 8u; ++checkpoint_i9) checkpoint_memory9 = (checkpoint_memory9 << 5u) ^ (checkpoint_memory9 >> 2u) ^ memory[checkpoint_i9];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory9;
    #endif
    return checkpoint_result9 ^ (checkpoint_memory9 << 11u | checkpoint_memory9 >> 21u);
    #endif
    #endif
    r[2] = r[5] * (r[4] | 1u) + 0x9e3779b9u;
    /* checkpoint 11: 80e55e04; registers: 86a5c819 78c7ceac c6e1ed51 07e22a2b 07e22a2b 293586c8 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 11
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 6u; ++checkpoint_i10) checkpoint_result10 = (checkpoint_result10 << 5u) ^ (checkpoint_result10 >> 2u) ^ r[checkpoint_i10];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result10;
    #endif
    u32 checkpoint_memory10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 8u; ++checkpoint_i10) checkpoint_memory10 = (checkpoint_memory10 << 5u) ^ (checkpoint_memory10 >> 2u) ^ memory[checkpoint_i10];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory10;
    #endif
    return checkpoint_result10 ^ (checkpoint_memory10 << 11u | checkpoint_memory10 >> 21u);
    #endif
    #endif
    u32 diff11 = r[2] - r[0]; r[3] = diff11 ^ (r[2] < r[0]);
    /* checkpoint 12: fca4f2ed; registers: 86a5c819 78c7ceac c6e1ed51 403c2538 07e22a2b 293586c8 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 12
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 6u; ++checkpoint_i11) checkpoint_result11 = (checkpoint_result11 << 5u) ^ (checkpoint_result11 >> 2u) ^ r[checkpoint_i11];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result11;
    #endif
    u32 checkpoint_memory11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 8u; ++checkpoint_i11) checkpoint_memory11 = (checkpoint_memory11 << 5u) ^ (checkpoint_memory11 >> 2u) ^ memory[checkpoint_i11];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory11;
    #endif
    return checkpoint_result11 ^ (checkpoint_memory11 << 11u | checkpoint_memory11 >> 21u);
    #endif
    #endif
    /* reference final registers: 86a5c819 78c7ceac c6e1ed51 403c2538 07e22a2b 293586c8 */
    /* reference final memory: f25d312d 07e2283b fffffbde 8f4e146c aec3a823 68445a34 7b9a0d33 e14b60b4 */
    u32 result = 0x9e3779b9u;
    for (u32 i = 0u; i < 6u; ++i) result = (result << 5u) ^ (result >> 2u) ^ r[i];
    u32 memory_result = 0x9e3779b9u;
    for (u32 i = 0u; i < 8u; ++i) memory_result = (memory_result << 5u) ^ (memory_result >> 2u) ^ memory[i];
    return result ^ ((memory_result << 11u) | (memory_result >> 21u));
}
#endif
