/* Generated by remu-casegen. Do not edit by hand.
* case: case_0598
* name: struct-by-value--carry-chain-array-scatter-sub-borrow-256
* category: abi-aggregates
* structural signature: carry-chain,array-scatter,sub-borrow,reverse-loop,mask-merge,divide-rem,sub-borrow,carry-chain,compare-select,compare-select,rotate-mix,switch-phi
* inspiration: https://gcc.gnu.org/onlinedocs/gccint/Testsuites.html#index-gcc_002ec_002dtorture
* kernel expected: 0x5b61b30c
* expected: 0x246aac3c
* Contract: freestanding ISO C unsigned arithmetic; no undefined behavior.
*/
typedef unsigned int u32;
typedef unsigned short u16;
typedef unsigned char u8;

static volatile u32 input[16] = { 0xdb86242bu, 0x00000100u, 0x04e19bedu, 0x152edc5fu, 0x3d06682du, 0x61b95864u, 0x5af8e679u, 0xffffffffu, 0xe0b1a27eu, 0x7520a464u, 0xa92279b4u, 0x15682a54u, 0x733c43b2u, 0x9a5e242du, 0x22c90087u, 0x5d5d3f95u };
struct packet { u32 tag; u16 length; u8 flags; u8 sequence; u32 payload; };
__attribute__((noinline)) static u32 consume(struct packet p)
{
    return p.tag + (p.payload << 5u | p.payload >> 27u) ^ (u32)p.length * 3u ^ ((u32)p.flags << 25u | (u32)p.flags >> 7u);
}

__attribute__((noinline)) static u32 remu_kernel(void)
{
    struct packet p = { input[0], (u16)input[1], (u8)input[2], (u8)input[3], input[3] };
    return consume(p);
}

#ifdef REMU_KERNEL_ONLY
__attribute__((noinline, used)) u32 remu_case(void)
{
    return remu_kernel();
}
#else
__attribute__((noinline, used)) u32 remu_case(void)
{
    u32 r[6];
    u32 memory[8];
    r[0] = remu_kernel();
    r[1] = input[7];
    r[2] = input[11];
    r[3] = input[15];
    r[4] = input[3];
    r[5] = 0x95965626u;
    memory[0] = input[0] ^ 0x00000256u;
    memory[1] = input[1] ^ 0x000004acu;
    memory[2] = input[2] ^ 0x00000958u;
    memory[3] = input[3] ^ 0x000012b0u;
    memory[4] = input[4] ^ 0x00002560u;
    memory[5] = input[5] ^ 0x00004ac0u;
    memory[6] = input[6] ^ 0x00009580u;
    memory[7] = input[7] ^ 0x00012b00u;
    u32 low0 = r[3] + r[5], carry0 = low0 < r[3]; u32 high0 = r[2] + r[3] + carry0; r[2] = low0 ^ high0;
    /* checkpoint 1: 430a0860; registers: 5b61b30c ffffffff 8036fc52 5d5d3f95 152edc5f 95965626 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 1
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 6u; ++checkpoint_i0) checkpoint_result0 = (checkpoint_result0 << 5u) ^ (checkpoint_result0 >> 2u) ^ r[checkpoint_i0];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result0;
    #endif
    u32 checkpoint_memory0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 8u; ++checkpoint_i0) checkpoint_memory0 = (checkpoint_memory0 << 5u) ^ (checkpoint_memory0 >> 2u) ^ memory[checkpoint_i0];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory0;
    #endif
    return checkpoint_result0 ^ (checkpoint_memory0 << 11u | checkpoint_memory0 >> 21u);
    #endif
    #endif
    u32 index1 = r[5] & 7u; memory[index1] ^= r[0]; r[3] = (memory[index1] << 2u) | (memory[index1] >> 30u);
    /* checkpoint 2: 1e22b47b; registers: 5b61b30c ffffffff 8036fc52 066703d4 152edc5f 95965626 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 2
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 6u; ++checkpoint_i1) checkpoint_result1 = (checkpoint_result1 << 5u) ^ (checkpoint_result1 >> 2u) ^ r[checkpoint_i1];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result1;
    #endif
    u32 checkpoint_memory1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 8u; ++checkpoint_i1) checkpoint_memory1 = (checkpoint_memory1 << 5u) ^ (checkpoint_memory1 >> 2u) ^ memory[checkpoint_i1];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory1;
    #endif
    return checkpoint_result1 ^ (checkpoint_memory1 << 11u | checkpoint_memory1 >> 21u);
    #endif
    #endif
    u32 diff2 = r[5] - r[2]; r[3] = diff2 ^ (r[5] < r[2]);
    /* checkpoint 3: 7e7931db; registers: 5b61b30c ffffffff 8036fc52 155f59d4 152edc5f 95965626 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 3
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 6u; ++checkpoint_i2) checkpoint_result2 = (checkpoint_result2 << 5u) ^ (checkpoint_result2 >> 2u) ^ r[checkpoint_i2];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result2;
    #endif
    u32 checkpoint_memory2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 8u; ++checkpoint_i2) checkpoint_memory2 = (checkpoint_memory2 << 5u) ^ (checkpoint_memory2 >> 2u) ^ memory[checkpoint_i2];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory2;
    #endif
    return checkpoint_result2 ^ (checkpoint_memory2 << 11u | checkpoint_memory2 >> 21u);
    #endif
    #endif
    u32 source3 = r[1], reversed3 = 0u; for (u32 i3 = 0u; i3 < 32u; ++i3) { reversed3 = (reversed3 << 1u) | (source3 & 1u); source3 >>= 1u; } r[5] = reversed3 ^ r[1];
    /* checkpoint 4: ebef67fd; registers: 5b61b30c ffffffff 8036fc52 155f59d4 152edc5f 00000000 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 4
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 6u; ++checkpoint_i3) checkpoint_result3 = (checkpoint_result3 << 5u) ^ (checkpoint_result3 >> 2u) ^ r[checkpoint_i3];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result3;
    #endif
    u32 checkpoint_memory3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 8u; ++checkpoint_i3) checkpoint_memory3 = (checkpoint_memory3 << 5u) ^ (checkpoint_memory3 >> 2u) ^ memory[checkpoint_i3];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory3;
    #endif
    return checkpoint_result3 ^ (checkpoint_memory3 << 11u | checkpoint_memory3 >> 21u);
    #endif
    #endif
    u32 mask4 = (r[0] << 7u) | (r[0] >> 25u); r[2] = (r[0] & mask4) | (r[5] & ~mask4);
    /* checkpoint 5: 61111aa0; registers: 5b61b30c ffffffff 1041820c 155f59d4 152edc5f 00000000 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 5
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 6u; ++checkpoint_i4) checkpoint_result4 = (checkpoint_result4 << 5u) ^ (checkpoint_result4 >> 2u) ^ r[checkpoint_i4];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result4;
    #endif
    u32 checkpoint_memory4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 8u; ++checkpoint_i4) checkpoint_memory4 = (checkpoint_memory4 << 5u) ^ (checkpoint_memory4 >> 2u) ^ memory[checkpoint_i4];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory4;
    #endif
    return checkpoint_result4 ^ (checkpoint_memory4 << 11u | checkpoint_memory4 >> 21u);
    #endif
    #endif
    u32 divisor5 = (r[1] & 0xffffu) | 1u; u32 rem5 = r[0] % divisor5; r[1] = (r[0] / divisor5) ^ (rem5 << 9u | rem5 >> 23u);
    /* checkpoint 6: 143eda90; registers: 5b61b30c 001c8762 1041820c 155f59d4 152edc5f 00000000 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 6
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 6u; ++checkpoint_i5) checkpoint_result5 = (checkpoint_result5 << 5u) ^ (checkpoint_result5 >> 2u) ^ r[checkpoint_i5];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result5;
    #endif
    u32 checkpoint_memory5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 8u; ++checkpoint_i5) checkpoint_memory5 = (checkpoint_memory5 << 5u) ^ (checkpoint_memory5 >> 2u) ^ memory[checkpoint_i5];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory5;
    #endif
    return checkpoint_result5 ^ (checkpoint_memory5 << 11u | checkpoint_memory5 >> 21u);
    #endif
    #endif
    u32 diff6 = r[2] - r[1]; r[4] = diff6 ^ (r[2] < r[1]);
    /* checkpoint 7: b4388d8d; registers: 5b61b30c 001c8762 1041820c 155f59d4 1024faaa 00000000 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 7
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 6u; ++checkpoint_i6) checkpoint_result6 = (checkpoint_result6 << 5u) ^ (checkpoint_result6 >> 2u) ^ r[checkpoint_i6];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result6;
    #endif
    u32 checkpoint_memory6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 8u; ++checkpoint_i6) checkpoint_memory6 = (checkpoint_memory6 << 5u) ^ (checkpoint_memory6 >> 2u) ^ memory[checkpoint_i6];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory6;
    #endif
    return checkpoint_result6 ^ (checkpoint_memory6 << 11u | checkpoint_memory6 >> 21u);
    #endif
    #endif
    u32 low7 = r[4] + r[5], carry7 = low7 < r[4]; u32 high7 = r[1] + r[2] + carry7; r[1] = low7 ^ high7;
    /* checkpoint 8: 2e58aa68; registers: 5b61b30c 007af3c4 1041820c 155f59d4 1024faaa 00000000 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 8
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 6u; ++checkpoint_i7) checkpoint_result7 = (checkpoint_result7 << 5u) ^ (checkpoint_result7 >> 2u) ^ r[checkpoint_i7];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result7;
    #endif
    u32 checkpoint_memory7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 8u; ++checkpoint_i7) checkpoint_memory7 = (checkpoint_memory7 << 5u) ^ (checkpoint_memory7 >> 2u) ^ memory[checkpoint_i7];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory7;
    #endif
    return checkpoint_result7 ^ (checkpoint_memory7 << 11u | checkpoint_memory7 >> 21u);
    #endif
    #endif
    r[1] = (r[4] < r[2]) ? r[4] + 0x10204081u : r[2] - 0x01020408u;
    /* checkpoint 9: 6088f671; registers: 5b61b30c 20453b2b 1041820c 155f59d4 1024faaa 00000000 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 9
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 6u; ++checkpoint_i8) checkpoint_result8 = (checkpoint_result8 << 5u) ^ (checkpoint_result8 >> 2u) ^ r[checkpoint_i8];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result8;
    #endif
    u32 checkpoint_memory8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 8u; ++checkpoint_i8) checkpoint_memory8 = (checkpoint_memory8 << 5u) ^ (checkpoint_memory8 >> 2u) ^ memory[checkpoint_i8];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory8;
    #endif
    return checkpoint_result8 ^ (checkpoint_memory8 << 11u | checkpoint_memory8 >> 21u);
    #endif
    #endif
    r[3] = (r[2] < r[4]) ? r[2] + 0x10204081u : r[4] - 0x01020408u;
    /* checkpoint 10: 5792f496; registers: 5b61b30c 20453b2b 1041820c 0f22f6a2 1024faaa 00000000 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 10
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 6u; ++checkpoint_i9) checkpoint_result9 = (checkpoint_result9 << 5u) ^ (checkpoint_result9 >> 2u) ^ r[checkpoint_i9];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result9;
    #endif
    u32 checkpoint_memory9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 8u; ++checkpoint_i9) checkpoint_memory9 = (checkpoint_memory9 << 5u) ^ (checkpoint_memory9 >> 2u) ^ memory[checkpoint_i9];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory9;
    #endif
    return checkpoint_result9 ^ (checkpoint_memory9 << 11u | checkpoint_memory9 >> 21u);
    #endif
    #endif
    u32 shift10 = r[0] & 31u; r[1] = (shift10 == 0u ? r[5] : (r[5] << shift10) | (r[5] >> (32u - shift10))) ^ (((shift10 + 7u) & 31u) == 0u ? r[0] : (r[0] >> ((shift10 + 7u) & 31u)) | (r[0] << (32u - ((shift10 + 7u) & 31u))));
    /* checkpoint 11: 5bf4b1e7; registers: 5b61b30c 36618b6c 1041820c 0f22f6a2 1024faaa 00000000 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 11
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 6u; ++checkpoint_i10) checkpoint_result10 = (checkpoint_result10 << 5u) ^ (checkpoint_result10 >> 2u) ^ r[checkpoint_i10];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result10;
    #endif
    u32 checkpoint_memory10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 8u; ++checkpoint_i10) checkpoint_memory10 = (checkpoint_memory10 << 5u) ^ (checkpoint_memory10 >> 2u) ^ memory[checkpoint_i10];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory10;
    #endif
    return checkpoint_result10 ^ (checkpoint_memory10 << 11u | checkpoint_memory10 >> 21u);
    #endif
    #endif
    switch (r[3] & 3u) { case 0u: r[2] = r[5] + r[3]; break; case 1u: r[2] = r[5] - r[3]; break; case 2u: r[2] = r[5] ^ (r[3] << 5u | r[3] >> 27u); break; default: r[2] = r[5] * 3u ^ r[3]; break; }
    /* checkpoint 12: 246aac3c; registers: 5b61b30c 36618b6c e45ed441 0f22f6a2 1024faaa 00000000 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 12
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 6u; ++checkpoint_i11) checkpoint_result11 = (checkpoint_result11 << 5u) ^ (checkpoint_result11 >> 2u) ^ r[checkpoint_i11];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result11;
    #endif
    u32 checkpoint_memory11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 8u; ++checkpoint_i11) checkpoint_memory11 = (checkpoint_memory11 << 5u) ^ (checkpoint_memory11 >> 2u) ^ memory[checkpoint_i11];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory11;
    #endif
    return checkpoint_result11 ^ (checkpoint_memory11 << 11u | checkpoint_memory11 >> 21u);
    #endif
    #endif
    /* reference final registers: 5b61b30c 36618b6c e45ed441 0f22f6a2 1024faaa 00000000 */
    /* reference final memory: db86267d 000005ac 04e192b5 152eceef 3d064d4d 61b912a4 0199c0f5 fffed4ff */
    u32 result = 0x9e3779b9u;
    for (u32 i = 0u; i < 6u; ++i) result = (result << 5u) ^ (result >> 2u) ^ r[i];
    u32 memory_result = 0x9e3779b9u;
    for (u32 i = 0u; i < 8u; ++i) memory_result = (memory_result << 5u) ^ (memory_result >> 2u) ^ memory[i];
    return result ^ ((memory_result << 11u) | (memory_result >> 21u));
}
#endif
