/* Generated by remu-casegen. Do not edit by hand.
* case: case_0486
* name: protocol-state-machine--compare-select-divide-rem-sub-borrow-1e6
* category: control-flow
* structural signature: compare-select,divide-rem,sub-borrow,halfword-swap,compare-select,halfword-swap,short-circuit,horner-loop,sub-borrow,carry-chain,carry-chain,popcount-loop
* inspiration: https://github.com/embench/embench-iot
* kernel expected: 0x00000000
* expected: 0xf9f3b271
* Contract: freestanding ISO C unsigned arithmetic; no undefined behavior.
*/
typedef unsigned int u32;
typedef unsigned short u16;
typedef unsigned char u8;

static volatile u32 input[16] = { 0x049ecb71u, 0x27d68016u, 0x0894d37du, 0x24f29992u, 0x32801114u, 0xe8a77b7fu, 0x8c150881u, 0x34c934fdu, 0xe545f4b8u, 0x5d825d50u, 0xfedde8c9u, 0xffffffffu, 0xb80ffff4u, 0xee84f0f8u, 0xc7c06cacu, 0x750a765cu };

__attribute__((noinline)) static u32 remu_kernel(void)
{
    u32 state = 0u, accepted = 0u;
    for (u32 i = 0u; i < 15u; ++i) {
        u32 symbol = input[i] & 3u;
        if (state == 0u && symbol == 1u) state = 1u;
        else if (state == 1u && symbol == 2u) state = 2u;
        else if (state == 2u && symbol == 3u) { ++accepted; state = 0u; }
        else if (symbol == 1u) state = 1u; else state = 0u;
    }
    return (accepted << 16u) | state;
}

#ifdef REMU_KERNEL_ONLY
__attribute__((noinline, used)) u32 remu_case(void)
{
    return remu_kernel();
}
#else
__attribute__((noinline, used)) u32 remu_case(void)
{
    u32 r[6];
    u32 memory[8];
    r[0] = remu_kernel();
    r[1] = input[7];
    r[2] = input[11];
    r[3] = input[15];
    r[4] = input[3];
    r[5] = 0x5d511536u;
    memory[0] = input[0] ^ 0x000001e6u;
    memory[1] = input[1] ^ 0x000003ccu;
    memory[2] = input[2] ^ 0x00000798u;
    memory[3] = input[3] ^ 0x00000f30u;
    memory[4] = input[4] ^ 0x00001e60u;
    memory[5] = input[5] ^ 0x00003cc0u;
    memory[6] = input[6] ^ 0x00007980u;
    memory[7] = input[7] ^ 0x0000f300u;
    r[2] = (r[0] < r[3]) ? r[0] + 0x10204081u : r[3] - 0x01020408u;
    /* checkpoint 1: 27568e5c; registers: 00000000 34c934fd 10204081 750a765c 24f29992 5d511536 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 1
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 6u; ++checkpoint_i0) checkpoint_result0 = (checkpoint_result0 << 5u) ^ (checkpoint_result0 >> 2u) ^ r[checkpoint_i0];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result0;
    #endif
    u32 checkpoint_memory0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 8u; ++checkpoint_i0) checkpoint_memory0 = (checkpoint_memory0 << 5u) ^ (checkpoint_memory0 >> 2u) ^ memory[checkpoint_i0];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory0;
    #endif
    return checkpoint_result0 ^ (checkpoint_memory0 << 11u | checkpoint_memory0 >> 21u);
    #endif
    #endif
    u32 divisor1 = (r[5] & 0xffffu) | 1u; u32 rem1 = r[4] % divisor1; r[3] = (r[4] / divisor1) ^ (rem1 << 9u | rem1 >> 23u);
    /* checkpoint 2: 98b0788c; registers: 00000000 34c934fd 10204081 00045bd9 24f29992 5d511536 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 2
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 6u; ++checkpoint_i1) checkpoint_result1 = (checkpoint_result1 << 5u) ^ (checkpoint_result1 >> 2u) ^ r[checkpoint_i1];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result1;
    #endif
    u32 checkpoint_memory1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 8u; ++checkpoint_i1) checkpoint_memory1 = (checkpoint_memory1 << 5u) ^ (checkpoint_memory1 >> 2u) ^ memory[checkpoint_i1];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory1;
    #endif
    return checkpoint_result1 ^ (checkpoint_memory1 << 11u | checkpoint_memory1 >> 21u);
    #endif
    #endif
    u32 diff2 = r[5] - r[3]; r[4] = diff2 ^ (r[5] < r[3]);
    /* checkpoint 3: b11be95f; registers: 00000000 34c934fd 10204081 00045bd9 5d4cb95d 5d511536 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 3
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 6u; ++checkpoint_i2) checkpoint_result2 = (checkpoint_result2 << 5u) ^ (checkpoint_result2 >> 2u) ^ r[checkpoint_i2];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result2;
    #endif
    u32 checkpoint_memory2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 8u; ++checkpoint_i2) checkpoint_memory2 = (checkpoint_memory2 << 5u) ^ (checkpoint_memory2 >> 2u) ^ memory[checkpoint_i2];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory2;
    #endif
    return checkpoint_result2 ^ (checkpoint_memory2 << 11u | checkpoint_memory2 >> 21u);
    #endif
    #endif
    r[5] = (r[1] << 16u | r[1] >> 16u) ^ (r[0] & 0xffff0000u);
    /* checkpoint 4: d8b7c8a0; registers: 00000000 34c934fd 10204081 00045bd9 5d4cb95d 34fd34c9 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 4
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 6u; ++checkpoint_i3) checkpoint_result3 = (checkpoint_result3 << 5u) ^ (checkpoint_result3 >> 2u) ^ r[checkpoint_i3];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result3;
    #endif
    u32 checkpoint_memory3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 8u; ++checkpoint_i3) checkpoint_memory3 = (checkpoint_memory3 << 5u) ^ (checkpoint_memory3 >> 2u) ^ memory[checkpoint_i3];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory3;
    #endif
    return checkpoint_result3 ^ (checkpoint_memory3 << 11u | checkpoint_memory3 >> 21u);
    #endif
    #endif
    r[5] = (r[5] < r[0]) ? r[5] + 0x10204081u : r[0] - 0x01020408u;
    /* checkpoint 5: 12b70791; registers: 00000000 34c934fd 10204081 00045bd9 5d4cb95d fefdfbf8 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 5
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 6u; ++checkpoint_i4) checkpoint_result4 = (checkpoint_result4 << 5u) ^ (checkpoint_result4 >> 2u) ^ r[checkpoint_i4];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result4;
    #endif
    u32 checkpoint_memory4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 8u; ++checkpoint_i4) checkpoint_memory4 = (checkpoint_memory4 << 5u) ^ (checkpoint_memory4 >> 2u) ^ memory[checkpoint_i4];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory4;
    #endif
    return checkpoint_result4 ^ (checkpoint_memory4 << 11u | checkpoint_memory4 >> 21u);
    #endif
    #endif
    r[1] = (r[4] << 16u | r[4] >> 16u) ^ (r[3] & 0xffff0000u);
    /* checkpoint 6: ad2ab7a0; registers: 00000000 b9595d4c 10204081 00045bd9 5d4cb95d fefdfbf8 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 6
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 6u; ++checkpoint_i5) checkpoint_result5 = (checkpoint_result5 << 5u) ^ (checkpoint_result5 >> 2u) ^ r[checkpoint_i5];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result5;
    #endif
    u32 checkpoint_memory5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 8u; ++checkpoint_i5) checkpoint_memory5 = (checkpoint_memory5 << 5u) ^ (checkpoint_memory5 >> 2u) ^ memory[checkpoint_i5];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory5;
    #endif
    return checkpoint_result5 ^ (checkpoint_memory5 << 11u | checkpoint_memory5 >> 21u);
    #endif
    #endif
    u32 effects6 = r[4]; if ((r[0] & 1u) != 0u && (effects6 += 3u, (r[0] & 2u) != 0u)) effects6 ^= 0x55aa55aau; r[5] = effects6;
    /* checkpoint 7: 0e9bf505; registers: 00000000 b9595d4c 10204081 00045bd9 5d4cb95d 5d4cb95d */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 7
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 6u; ++checkpoint_i6) checkpoint_result6 = (checkpoint_result6 << 5u) ^ (checkpoint_result6 >> 2u) ^ r[checkpoint_i6];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result6;
    #endif
    u32 checkpoint_memory6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 8u; ++checkpoint_i6) checkpoint_memory6 = (checkpoint_memory6 << 5u) ^ (checkpoint_memory6 >> 2u) ^ memory[checkpoint_i6];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory6;
    #endif
    return checkpoint_result6 ^ (checkpoint_memory6 << 11u | checkpoint_memory6 >> 21u);
    #endif
    #endif
    u32 polynomial7 = r[3]; const u32 coefficient7[4] = { 3u, 5u, 17u, 257u }; for (u32 i7 = 0u; i7 < 4u; ++i7) polynomial7 = polynomial7 * (r[4] | 1u) + coefficient7[i7]; r[1] = polynomial7;
    /* checkpoint 8: 87b8ae1c; registers: 00000000 6a618d53 10204081 00045bd9 5d4cb95d 5d4cb95d */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 8
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 6u; ++checkpoint_i7) checkpoint_result7 = (checkpoint_result7 << 5u) ^ (checkpoint_result7 >> 2u) ^ r[checkpoint_i7];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result7;
    #endif
    u32 checkpoint_memory7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 8u; ++checkpoint_i7) checkpoint_memory7 = (checkpoint_memory7 << 5u) ^ (checkpoint_memory7 >> 2u) ^ memory[checkpoint_i7];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory7;
    #endif
    return checkpoint_result7 ^ (checkpoint_memory7 << 11u | checkpoint_memory7 >> 21u);
    #endif
    #endif
    u32 diff8 = r[0] - r[1]; r[0] = diff8 ^ (r[0] < r[1]);
    /* checkpoint 9: fd9e6504; registers: 959e72ac 6a618d53 10204081 00045bd9 5d4cb95d 5d4cb95d */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 9
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 6u; ++checkpoint_i8) checkpoint_result8 = (checkpoint_result8 << 5u) ^ (checkpoint_result8 >> 2u) ^ r[checkpoint_i8];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result8;
    #endif
    u32 checkpoint_memory8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 8u; ++checkpoint_i8) checkpoint_memory8 = (checkpoint_memory8 << 5u) ^ (checkpoint_memory8 >> 2u) ^ memory[checkpoint_i8];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory8;
    #endif
    return checkpoint_result8 ^ (checkpoint_memory8 << 11u | checkpoint_memory8 >> 21u);
    #endif
    #endif
    u32 low9 = r[3] + r[0], carry9 = low9 < r[3]; u32 high9 = r[2] + r[3] + carry9; r[2] = low9 ^ high9;
    /* checkpoint 10: dbb985e9; registers: 959e72ac 6a618d53 858652df 00045bd9 5d4cb95d 5d4cb95d */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 10
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 6u; ++checkpoint_i9) checkpoint_result9 = (checkpoint_result9 << 5u) ^ (checkpoint_result9 >> 2u) ^ r[checkpoint_i9];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result9;
    #endif
    u32 checkpoint_memory9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 8u; ++checkpoint_i9) checkpoint_memory9 = (checkpoint_memory9 << 5u) ^ (checkpoint_memory9 >> 2u) ^ memory[checkpoint_i9];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory9;
    #endif
    return checkpoint_result9 ^ (checkpoint_memory9 << 11u | checkpoint_memory9 >> 21u);
    #endif
    #endif
    u32 low10 = r[2] + r[3], carry10 = low10 < r[2]; u32 high10 = r[5] + r[0] + carry10; r[5] = low10 ^ high10;
    /* checkpoint 11: f194be05; registers: 959e72ac 6a618d53 858652df 00045bd9 5d4cb95d 776182b1 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 11
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 6u; ++checkpoint_i10) checkpoint_result10 = (checkpoint_result10 << 5u) ^ (checkpoint_result10 >> 2u) ^ r[checkpoint_i10];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result10;
    #endif
    u32 checkpoint_memory10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 8u; ++checkpoint_i10) checkpoint_memory10 = (checkpoint_memory10 << 5u) ^ (checkpoint_memory10 >> 2u) ^ memory[checkpoint_i10];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory10;
    #endif
    return checkpoint_result10 ^ (checkpoint_memory10 << 11u | checkpoint_memory10 >> 21u);
    #endif
    #endif
    u32 bits11 = r[3], count11 = 0u; while (bits11 != 0u) { bits11 &= bits11 - 1u; ++count11; } r[1] = count11 ^ r[4];
    /* checkpoint 12: f9f3b271; registers: 959e72ac 5d4cb956 858652df 00045bd9 5d4cb95d 776182b1 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 12
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 6u; ++checkpoint_i11) checkpoint_result11 = (checkpoint_result11 << 5u) ^ (checkpoint_result11 >> 2u) ^ r[checkpoint_i11];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result11;
    #endif
    u32 checkpoint_memory11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 8u; ++checkpoint_i11) checkpoint_memory11 = (checkpoint_memory11 << 5u) ^ (checkpoint_memory11 >> 2u) ^ memory[checkpoint_i11];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory11;
    #endif
    return checkpoint_result11 ^ (checkpoint_memory11 << 11u | checkpoint_memory11 >> 21u);
    #endif
    #endif
    /* reference final registers: 959e72ac 5d4cb956 858652df 00045bd9 5d4cb95d 776182b1 */
    /* reference final memory: 049eca97 27d683da 0894d4e5 24f296a2 32800f74 e8a747bf 8c157101 34c9c7fd */
    u32 result = 0x9e3779b9u;
    for (u32 i = 0u; i < 6u; ++i) result = (result << 5u) ^ (result >> 2u) ^ r[i];
    u32 memory_result = 0x9e3779b9u;
    for (u32 i = 0u; i < 8u; ++i) memory_result = (memory_result << 5u) ^ (memory_result >> 2u) ^ memory[i];
    return result ^ ((memory_result << 11u) | (memory_result >> 21u));
}
#endif
