/* Generated by renvo-casegen. Do not edit by hand.
* case: case_0190
* name: reverse-and-rotate--counted-loop-array-scatter-add-carry-0be
* category: bit-manipulation
* structural signature: counted-loop,array-scatter,add-carry,minmax-clamp,endian-swap,horner-loop,byte-pack,multiply-low,gray-decode,counted-loop,switch-phi,compare-select
* inspiration: https://gcc.gnu.org/onlinedocs/gccint/Testsuites.html#index-gcc_002ec_002dtorture
* kernel expected: 0xc0030000
* expected: 0xba1ff17f
* Contract: freestanding ISO C unsigned arithmetic; no undefined behavior.
*/
typedef unsigned int u32;
typedef unsigned short u16;
typedef unsigned char u8;

static volatile u32 input[16] = { 0xaa019c7du, 0x179422b5u, 0x345b213eu, 0xc7db2f89u, 0xc18416ccu, 0x2b0dd9b5u, 0xccdffbe5u, 0xb956aaecu, 0xd862aee7u, 0x00000003u, 0x063e6d8fu, 0x79bb2020u, 0x3109a593u, 0x60603754u, 0x49d581ddu, 0x00000003u };

__attribute__((noinline)) static u32 renvo_kernel(void)
{
    u32 x = input[15], reversed = 0u;
    for (u32 i = 0u; i < 32u; ++i) { reversed = (reversed << 1u) | (x & 1u); x >>= 1u; }
    x = input[15];
    return reversed ^ ((x << 16u) | (x >> 16u));
}

#ifdef RENVO_KERNEL_ONLY
__attribute__((noinline, used)) u32 renvo_case(void)
{
    return renvo_kernel();
}
#else
__attribute__((noinline, used)) u32 renvo_case(void)
{
    u32 r[6];
    u32 memory[8];
    r[0] = renvo_kernel();
    r[1] = input[15];
    r[2] = input[3];
    r[3] = input[7];
    r[4] = input[11];
    r[5] = 0x6d2c574eu;
    memory[0] = input[0] ^ 0x000000beu;
    memory[1] = input[1] ^ 0x0000017cu;
    memory[2] = input[2] ^ 0x000002f8u;
    memory[3] = input[3] ^ 0x000005f0u;
    memory[4] = input[4] ^ 0x00000be0u;
    memory[5] = input[5] ^ 0x000017c0u;
    memory[6] = input[6] ^ 0x00002f80u;
    memory[7] = input[7] ^ 0x00005f00u;
    u32 loop0 = r[2]; for (u32 i0 = 0u; i0 < 3u; ++i0) { loop0 += r[5] ^ i0; loop0 = loop0 << 3u | loop0 >> 29u; } r[0] = loop0;
    /* checkpoint 1: 59b61fc0; registers: c3863c60 00000003 c7db2f89 b956aaec 79bb2020 6d2c574e */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 1
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 6u; ++checkpoint_i0) checkpoint_result0 = (checkpoint_result0 << 5u) ^ (checkpoint_result0 >> 2u) ^ r[checkpoint_i0];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result0;
    #endif
    u32 checkpoint_memory0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 8u; ++checkpoint_i0) checkpoint_memory0 = (checkpoint_memory0 << 5u) ^ (checkpoint_memory0 >> 2u) ^ memory[checkpoint_i0];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory0;
    #endif
    return checkpoint_result0 ^ (checkpoint_memory0 << 11u | checkpoint_memory0 >> 21u);
    #endif
    #endif
    u32 index1 = r[2] & 7u; memory[index1] ^= r[0]; r[4] = (memory[index1] << 2u) | (memory[index1] >> 30u);
    /* checkpoint 2: c9e208a2; registers: c3863c60 00000003 c7db2f89 b956aaec 50487ea7 6d2c574e */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 2
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 6u; ++checkpoint_i1) checkpoint_result1 = (checkpoint_result1 << 5u) ^ (checkpoint_result1 >> 2u) ^ r[checkpoint_i1];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result1;
    #endif
    u32 checkpoint_memory1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 8u; ++checkpoint_i1) checkpoint_memory1 = (checkpoint_memory1 << 5u) ^ (checkpoint_memory1 >> 2u) ^ memory[checkpoint_i1];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory1;
    #endif
    return checkpoint_result1 ^ (checkpoint_memory1 << 11u | checkpoint_memory1 >> 21u);
    #endif
    #endif
    u32 sum2 = r[2] + r[5]; r[5] = sum2 ^ (sum2 < r[2]);
    /* checkpoint 3: 91c9d93a; registers: c3863c60 00000003 c7db2f89 b956aaec 50487ea7 350786d6 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 3
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 6u; ++checkpoint_i2) checkpoint_result2 = (checkpoint_result2 << 5u) ^ (checkpoint_result2 >> 2u) ^ r[checkpoint_i2];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result2;
    #endif
    u32 checkpoint_memory2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 8u; ++checkpoint_i2) checkpoint_memory2 = (checkpoint_memory2 << 5u) ^ (checkpoint_memory2 >> 2u) ^ memory[checkpoint_i2];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory2;
    #endif
    return checkpoint_result2 ^ (checkpoint_memory2 << 11u | checkpoint_memory2 >> 21u);
    #endif
    #endif
    u32 low3 = r[4] < r[3] ? r[4] : r[3], high3 = r[4] > r[3] ? r[4] : r[3]; u32 clamp3 = r[0] < low3 ? low3 : (r[0] > high3 ? high3 : r[0]); r[0] = clamp3 ^ low3 ^ high3;
    /* checkpoint 4: 1884c2ba; registers: 50487ea7 00000003 c7db2f89 b956aaec 50487ea7 350786d6 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 4
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 6u; ++checkpoint_i3) checkpoint_result3 = (checkpoint_result3 << 5u) ^ (checkpoint_result3 >> 2u) ^ r[checkpoint_i3];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result3;
    #endif
    u32 checkpoint_memory3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 8u; ++checkpoint_i3) checkpoint_memory3 = (checkpoint_memory3 << 5u) ^ (checkpoint_memory3 >> 2u) ^ memory[checkpoint_i3];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory3;
    #endif
    return checkpoint_result3 ^ (checkpoint_memory3 << 11u | checkpoint_memory3 >> 21u);
    #endif
    #endif
    u32 endian4 = ((r[2] & 0xffu) << 24u) | ((r[2] & 0xff00u) << 8u) | ((r[2] >> 8u) & 0xff00u) | (r[2] >> 24u); r[3] = endian4 ^ (r[4] << 8u | r[4] >> 24u);
    /* checkpoint 5: c05d53c5; registers: 50487ea7 00000003 c7db2f89 c1517c97 50487ea7 350786d6 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 5
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 6u; ++checkpoint_i4) checkpoint_result4 = (checkpoint_result4 << 5u) ^ (checkpoint_result4 >> 2u) ^ r[checkpoint_i4];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result4;
    #endif
    u32 checkpoint_memory4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 8u; ++checkpoint_i4) checkpoint_memory4 = (checkpoint_memory4 << 5u) ^ (checkpoint_memory4 >> 2u) ^ memory[checkpoint_i4];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory4;
    #endif
    return checkpoint_result4 ^ (checkpoint_memory4 << 11u | checkpoint_memory4 >> 21u);
    #endif
    #endif
    u32 polynomial5 = r[0]; const u32 coefficient5[4] = { 3u, 5u, 17u, 257u }; for (u32 i5 = 0u; i5 < 4u; ++i5) polynomial5 = polynomial5 * (r[3] | 1u) + coefficient5[i5]; r[0] = polynomial5;
    /* checkpoint 6: 61f9073a; registers: f7a60bf9 00000003 c7db2f89 c1517c97 50487ea7 350786d6 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 6
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 6u; ++checkpoint_i5) checkpoint_result5 = (checkpoint_result5 << 5u) ^ (checkpoint_result5 >> 2u) ^ r[checkpoint_i5];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result5;
    #endif
    u32 checkpoint_memory5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 8u; ++checkpoint_i5) checkpoint_memory5 = (checkpoint_memory5 << 5u) ^ (checkpoint_memory5 >> 2u) ^ memory[checkpoint_i5];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory5;
    #endif
    return checkpoint_result5 ^ (checkpoint_memory5 << 11u | checkpoint_memory5 >> 21u);
    #endif
    #endif
    r[0] = (r[0] & 0xffu) | ((r[5] & 0xffu) << 8u) | (((r[0] >> 8u) & 0xffu) << 16u) | (((r[5] >> 8u) & 0xffu) << 24u);
    /* checkpoint 7: 61d0d7ed; registers: 860bd6f9 00000003 c7db2f89 c1517c97 50487ea7 350786d6 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 7
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 6u; ++checkpoint_i6) checkpoint_result6 = (checkpoint_result6 << 5u) ^ (checkpoint_result6 >> 2u) ^ r[checkpoint_i6];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result6;
    #endif
    u32 checkpoint_memory6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 8u; ++checkpoint_i6) checkpoint_memory6 = (checkpoint_memory6 << 5u) ^ (checkpoint_memory6 >> 2u) ^ memory[checkpoint_i6];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory6;
    #endif
    return checkpoint_result6 ^ (checkpoint_memory6 << 11u | checkpoint_memory6 >> 21u);
    #endif
    #endif
    r[0] = r[3] * (r[5] | 1u) + 0x9e3779b9u;
    /* checkpoint 8: 329d37c7; registers: 4bff268a 00000003 c7db2f89 c1517c97 50487ea7 350786d6 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 8
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 6u; ++checkpoint_i7) checkpoint_result7 = (checkpoint_result7 << 5u) ^ (checkpoint_result7 >> 2u) ^ r[checkpoint_i7];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result7;
    #endif
    u32 checkpoint_memory7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 8u; ++checkpoint_i7) checkpoint_memory7 = (checkpoint_memory7 << 5u) ^ (checkpoint_memory7 >> 2u) ^ memory[checkpoint_i7];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory7;
    #endif
    return checkpoint_result7 ^ (checkpoint_memory7 << 11u | checkpoint_memory7 >> 21u);
    #endif
    #endif
    u32 gray8 = r[5] ^ (r[5] >> 1u); gray8 ^= gray8 >> 1u; gray8 ^= gray8 >> 2u; gray8 ^= gray8 >> 4u; gray8 ^= gray8 >> 8u; gray8 ^= gray8 >> 16u; r[3] = gray8 ^ r[5];
    /* checkpoint 9: 7b7a7c16; registers: 4bff268a 00000003 c7db2f89 00000000 50487ea7 350786d6 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 9
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 6u; ++checkpoint_i8) checkpoint_result8 = (checkpoint_result8 << 5u) ^ (checkpoint_result8 >> 2u) ^ r[checkpoint_i8];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result8;
    #endif
    u32 checkpoint_memory8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 8u; ++checkpoint_i8) checkpoint_memory8 = (checkpoint_memory8 << 5u) ^ (checkpoint_memory8 >> 2u) ^ memory[checkpoint_i8];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory8;
    #endif
    return checkpoint_result8 ^ (checkpoint_memory8 << 11u | checkpoint_memory8 >> 21u);
    #endif
    #endif
    u32 loop9 = r[5]; for (u32 i9 = 0u; i9 < 7u; ++i9) { loop9 += r[1] ^ i9; loop9 = loop9 << 3u | loop9 >> 29u; } r[0] = loop9;
    /* checkpoint 10: 4b044bd1; registers: db2f3098 00000003 c7db2f89 00000000 50487ea7 350786d6 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 10
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 6u; ++checkpoint_i9) checkpoint_result9 = (checkpoint_result9 << 5u) ^ (checkpoint_result9 >> 2u) ^ r[checkpoint_i9];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result9;
    #endif
    u32 checkpoint_memory9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 8u; ++checkpoint_i9) checkpoint_memory9 = (checkpoint_memory9 << 5u) ^ (checkpoint_memory9 >> 2u) ^ memory[checkpoint_i9];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory9;
    #endif
    return checkpoint_result9 ^ (checkpoint_memory9 << 11u | checkpoint_memory9 >> 21u);
    #endif
    #endif
    switch (r[2] & 3u) { case 0u: r[2] = r[1] + r[2]; break; case 1u: r[2] = r[1] - r[2]; break; case 2u: r[2] = r[1] ^ (r[2] << 5u | r[2] >> 27u); break; default: r[2] = r[1] * 3u ^ r[2]; break; }
    /* checkpoint 11: 47023bc8; registers: db2f3098 00000003 3824d07a 00000000 50487ea7 350786d6 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 11
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 6u; ++checkpoint_i10) checkpoint_result10 = (checkpoint_result10 << 5u) ^ (checkpoint_result10 >> 2u) ^ r[checkpoint_i10];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result10;
    #endif
    u32 checkpoint_memory10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 8u; ++checkpoint_i10) checkpoint_memory10 = (checkpoint_memory10 << 5u) ^ (checkpoint_memory10 >> 2u) ^ memory[checkpoint_i10];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory10;
    #endif
    return checkpoint_result10 ^ (checkpoint_memory10 << 11u | checkpoint_memory10 >> 21u);
    #endif
    #endif
    r[4] = (r[4] < r[3]) ? r[4] + 0x10204081u : r[3] - 0x01020408u;
    /* checkpoint 12: ba1ff17f; registers: db2f3098 00000003 3824d07a 00000000 fefdfbf8 350786d6 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 12
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 6u; ++checkpoint_i11) checkpoint_result11 = (checkpoint_result11 << 5u) ^ (checkpoint_result11 >> 2u) ^ r[checkpoint_i11];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result11;
    #endif
    u32 checkpoint_memory11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 8u; ++checkpoint_i11) checkpoint_memory11 = (checkpoint_memory11 << 5u) ^ (checkpoint_memory11 >> 2u) ^ memory[checkpoint_i11];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory11;
    #endif
    return checkpoint_result11 ^ (checkpoint_memory11 << 11u | checkpoint_memory11 >> 21u);
    #endif
    #endif
    /* reference final registers: db2f3098 00000003 3824d07a 00000000 fefdfbf8 350786d6 */
    /* reference final memory: aa019cc3 d4121fa9 345b23c6 c7db2a79 c1841d2c 2b0dce75 ccdfd465 b956f5ec */
    u32 result = 0x9e3779b9u;
    for (u32 i = 0u; i < 6u; ++i) result = (result << 5u) ^ (result >> 2u) ^ r[i];
    u32 memory_result = 0x9e3779b9u;
    for (u32 i = 0u; i < 8u; ++i) memory_result = (memory_result << 5u) ^ (memory_result >> 2u) ^ memory[i];
    return result ^ ((memory_result << 11u) | (memory_result >> 21u));
}
#endif
