/* Generated by remu-casegen. Do not edit by hand.
* case: case_0271
* name: insertion-sort--switch-phi-popcount-loop-add-carry-10f
* category: algorithms
* structural signature: switch-phi,popcount-loop,add-carry,reverse-loop,array-scatter,divide-rem,byte-pack,add-carry,mask-merge,byte-pack,mask-merge,endian-swap
* inspiration: https://github.com/embench/embench-iot
* kernel expected: 0x7add1b43
* expected: 0xc4208faf
* Contract: freestanding ISO C unsigned arithmetic; no undefined behavior.
*/
typedef unsigned int u32;
typedef unsigned short u16;
typedef unsigned char u8;

static volatile u32 input[16] = { 0x31d3d1e3u, 0x53e280fdu, 0x4e7063d1u, 0x80000000u, 0x982eecebu, 0x80000000u, 0xc54db9b0u, 0x9372d002u, 0x30136100u, 0x059e0e1cu, 0xb3dca83eu, 0x7efe9fb2u, 0x4a2fca10u, 0xd265cec3u, 0xf21d3b2fu, 0xac081058u };

__attribute__((noinline)) static u32 remu_kernel(void)
{
    u32 a[16];
    for (u32 i = 0u; i < 13u; ++i) a[i] = input[i];
    for (u32 i = 1u; i < 13u; ++i) {
        u32 value = a[i], j = i;
        while (j != 0u && a[j - 1u] > value) { a[j] = a[j - 1u]; --j; }
        a[j] = value;
    }
    u32 result = 0x9e3779b9u;
    for (u32 i = 0u; i < 13u; ++i) result = (result << 5u) ^ (result >> 2u) ^ a[i];
    return result;
}

#ifdef REMU_KERNEL_ONLY
__attribute__((noinline, used)) u32 remu_case(void)
{
    return remu_kernel();
}
#else
__attribute__((noinline, used)) u32 remu_case(void)
{
    u32 r[6];
    u32 memory[8];
    r[0] = remu_kernel();
    r[1] = input[0];
    r[2] = input[4];
    r[3] = input[8];
    r[4] = input[12];
    r[5] = 0x7cb9dad7u;
    memory[0] = input[0] ^ 0x0000010fu;
    memory[1] = input[1] ^ 0x0000021eu;
    memory[2] = input[2] ^ 0x0000043cu;
    memory[3] = input[3] ^ 0x00000878u;
    memory[4] = input[4] ^ 0x000010f0u;
    memory[5] = input[5] ^ 0x000021e0u;
    memory[6] = input[6] ^ 0x000043c0u;
    memory[7] = input[7] ^ 0x00008780u;
    switch (r[3] & 3u) { case 0u: r[0] = r[5] + r[3]; break; case 1u: r[0] = r[5] - r[3]; break; case 2u: r[0] = r[5] ^ (r[3] << 5u | r[3] >> 27u); break; default: r[0] = r[5] * 3u ^ r[3]; break; }
    /* checkpoint 1: c0bfb6a6; registers: accd3bd7 31d3d1e3 982eeceb 30136100 4a2fca10 7cb9dad7 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 1
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 6u; ++checkpoint_i0) checkpoint_result0 = (checkpoint_result0 << 5u) ^ (checkpoint_result0 >> 2u) ^ r[checkpoint_i0];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result0;
    #endif
    u32 checkpoint_memory0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 8u; ++checkpoint_i0) checkpoint_memory0 = (checkpoint_memory0 << 5u) ^ (checkpoint_memory0 >> 2u) ^ memory[checkpoint_i0];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory0;
    #endif
    return checkpoint_result0 ^ (checkpoint_memory0 << 11u | checkpoint_memory0 >> 21u);
    #endif
    #endif
    u32 bits1 = r[3], count1 = 0u; while (bits1 != 0u) { bits1 &= bits1 - 1u; ++count1; } r[1] = count1 ^ r[0];
    /* checkpoint 2: afe2ab54; registers: accd3bd7 accd3bdf 982eeceb 30136100 4a2fca10 7cb9dad7 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 2
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 6u; ++checkpoint_i1) checkpoint_result1 = (checkpoint_result1 << 5u) ^ (checkpoint_result1 >> 2u) ^ r[checkpoint_i1];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result1;
    #endif
    u32 checkpoint_memory1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 8u; ++checkpoint_i1) checkpoint_memory1 = (checkpoint_memory1 << 5u) ^ (checkpoint_memory1 >> 2u) ^ memory[checkpoint_i1];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory1;
    #endif
    return checkpoint_result1 ^ (checkpoint_memory1 << 11u | checkpoint_memory1 >> 21u);
    #endif
    #endif
    u32 sum2 = r[5] + r[4]; r[2] = sum2 ^ (sum2 < r[5]);
    /* checkpoint 3: 80592a74; registers: accd3bd7 accd3bdf c6e9a4e7 30136100 4a2fca10 7cb9dad7 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 3
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 6u; ++checkpoint_i2) checkpoint_result2 = (checkpoint_result2 << 5u) ^ (checkpoint_result2 >> 2u) ^ r[checkpoint_i2];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result2;
    #endif
    u32 checkpoint_memory2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 8u; ++checkpoint_i2) checkpoint_memory2 = (checkpoint_memory2 << 5u) ^ (checkpoint_memory2 >> 2u) ^ memory[checkpoint_i2];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory2;
    #endif
    return checkpoint_result2 ^ (checkpoint_memory2 << 11u | checkpoint_memory2 >> 21u);
    #endif
    #endif
    u32 source3 = r[0], reversed3 = 0u; for (u32 i3 = 0u; i3 < 32u; ++i3) { reversed3 = (reversed3 << 1u) | (source3 & 1u); source3 >>= 1u; } r[3] = reversed3 ^ r[4];
    /* checkpoint 4: 8927bffe; registers: accd3bd7 accd3bdf c6e9a4e7 a1f37925 4a2fca10 7cb9dad7 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 4
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 6u; ++checkpoint_i3) checkpoint_result3 = (checkpoint_result3 << 5u) ^ (checkpoint_result3 >> 2u) ^ r[checkpoint_i3];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result3;
    #endif
    u32 checkpoint_memory3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 8u; ++checkpoint_i3) checkpoint_memory3 = (checkpoint_memory3 << 5u) ^ (checkpoint_memory3 >> 2u) ^ memory[checkpoint_i3];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory3;
    #endif
    return checkpoint_result3 ^ (checkpoint_memory3 << 11u | checkpoint_memory3 >> 21u);
    #endif
    #endif
    u32 index4 = r[0] & 7u; memory[index4] ^= r[2]; r[1] = (memory[index4] << 5u) | (memory[index4] >> 27u);
    /* checkpoint 5: 1f4f13c6; registers: accd3bd7 b37e6caa c6e9a4e7 a1f37925 4a2fca10 7cb9dad7 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 5
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 6u; ++checkpoint_i4) checkpoint_result4 = (checkpoint_result4 << 5u) ^ (checkpoint_result4 >> 2u) ^ r[checkpoint_i4];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result4;
    #endif
    u32 checkpoint_memory4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 8u; ++checkpoint_i4) checkpoint_memory4 = (checkpoint_memory4 << 5u) ^ (checkpoint_memory4 >> 2u) ^ memory[checkpoint_i4];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory4;
    #endif
    return checkpoint_result4 ^ (checkpoint_memory4 << 11u | checkpoint_memory4 >> 21u);
    #endif
    #endif
    u32 divisor5 = (r[3] & 0xffffu) | 1u; u32 rem5 = r[5] % divisor5; r[1] = (r[5] / divisor5) ^ (rem5 << 9u | rem5 >> 23u);
    /* checkpoint 6: e44c7db0; registers: accd3bd7 0072c391 c6e9a4e7 a1f37925 4a2fca10 7cb9dad7 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 6
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 6u; ++checkpoint_i5) checkpoint_result5 = (checkpoint_result5 << 5u) ^ (checkpoint_result5 >> 2u) ^ r[checkpoint_i5];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result5;
    #endif
    u32 checkpoint_memory5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 8u; ++checkpoint_i5) checkpoint_memory5 = (checkpoint_memory5 << 5u) ^ (checkpoint_memory5 >> 2u) ^ memory[checkpoint_i5];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory5;
    #endif
    return checkpoint_result5 ^ (checkpoint_memory5 << 11u | checkpoint_memory5 >> 21u);
    #endif
    #endif
    r[5] = (r[1] & 0xffu) | ((r[1] & 0xffu) << 8u) | (((r[1] >> 8u) & 0xffu) << 16u) | (((r[1] >> 8u) & 0xffu) << 24u);
    /* checkpoint 7: 5b3636f6; registers: accd3bd7 0072c391 c6e9a4e7 a1f37925 4a2fca10 c3c39191 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 7
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 6u; ++checkpoint_i6) checkpoint_result6 = (checkpoint_result6 << 5u) ^ (checkpoint_result6 >> 2u) ^ r[checkpoint_i6];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result6;
    #endif
    u32 checkpoint_memory6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 8u; ++checkpoint_i6) checkpoint_memory6 = (checkpoint_memory6 << 5u) ^ (checkpoint_memory6 >> 2u) ^ memory[checkpoint_i6];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory6;
    #endif
    return checkpoint_result6 ^ (checkpoint_memory6 << 11u | checkpoint_memory6 >> 21u);
    #endif
    #endif
    u32 sum7 = r[1] + r[1]; r[5] = sum7 ^ (sum7 < r[1]);
    /* checkpoint 8: 98102045; registers: accd3bd7 0072c391 c6e9a4e7 a1f37925 4a2fca10 00e58722 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 8
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 6u; ++checkpoint_i7) checkpoint_result7 = (checkpoint_result7 << 5u) ^ (checkpoint_result7 >> 2u) ^ r[checkpoint_i7];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result7;
    #endif
    u32 checkpoint_memory7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 8u; ++checkpoint_i7) checkpoint_memory7 = (checkpoint_memory7 << 5u) ^ (checkpoint_memory7 >> 2u) ^ memory[checkpoint_i7];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory7;
    #endif
    return checkpoint_result7 ^ (checkpoint_memory7 << 11u | checkpoint_memory7 >> 21u);
    #endif
    #endif
    u32 mask8 = (r[0] << 11u) | (r[0] >> 21u); r[5] = (r[0] & mask8) | (r[2] & ~mask8);
    /* checkpoint 9: 36189ea0; registers: accd3bd7 0072c391 c6e9a4e7 a1f37925 4a2fca10 aeed39c7 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 9
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 6u; ++checkpoint_i8) checkpoint_result8 = (checkpoint_result8 << 5u) ^ (checkpoint_result8 >> 2u) ^ r[checkpoint_i8];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result8;
    #endif
    u32 checkpoint_memory8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 8u; ++checkpoint_i8) checkpoint_memory8 = (checkpoint_memory8 << 5u) ^ (checkpoint_memory8 >> 2u) ^ memory[checkpoint_i8];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory8;
    #endif
    return checkpoint_result8 ^ (checkpoint_memory8 << 11u | checkpoint_memory8 >> 21u);
    #endif
    #endif
    r[0] = (r[0] & 0xffu) | ((r[3] & 0xffu) << 8u) | (((r[0] >> 8u) & 0xffu) << 16u) | (((r[3] >> 8u) & 0xffu) << 24u);
    /* checkpoint 10: 2a9320e7; registers: 793b25d7 0072c391 c6e9a4e7 a1f37925 4a2fca10 aeed39c7 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 10
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 6u; ++checkpoint_i9) checkpoint_result9 = (checkpoint_result9 << 5u) ^ (checkpoint_result9 >> 2u) ^ r[checkpoint_i9];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result9;
    #endif
    u32 checkpoint_memory9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 8u; ++checkpoint_i9) checkpoint_memory9 = (checkpoint_memory9 << 5u) ^ (checkpoint_memory9 >> 2u) ^ memory[checkpoint_i9];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory9;
    #endif
    return checkpoint_result9 ^ (checkpoint_memory9 << 11u | checkpoint_memory9 >> 21u);
    #endif
    #endif
    u32 mask10 = (r[5] << 13u) | (r[5] >> 19u); r[3] = (r[5] & mask10) | (r[4] & ~mask10);
    /* checkpoint 11: 1f6564c9; registers: 793b25d7 0072c391 c6e9a4e7 ee2f3bc5 4a2fca10 aeed39c7 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 11
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 6u; ++checkpoint_i10) checkpoint_result10 = (checkpoint_result10 << 5u) ^ (checkpoint_result10 >> 2u) ^ r[checkpoint_i10];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result10;
    #endif
    u32 checkpoint_memory10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 8u; ++checkpoint_i10) checkpoint_memory10 = (checkpoint_memory10 << 5u) ^ (checkpoint_memory10 >> 2u) ^ memory[checkpoint_i10];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory10;
    #endif
    return checkpoint_result10 ^ (checkpoint_memory10 << 11u | checkpoint_memory10 >> 21u);
    #endif
    #endif
    u32 endian11 = ((r[5] & 0xffu) << 24u) | ((r[5] & 0xff00u) << 8u) | ((r[5] >> 8u) & 0xff00u) | (r[5] >> 24u); r[1] = endian11 ^ (r[1] << 8u | r[1] >> 24u);
    /* checkpoint 12: c4208faf; registers: 793b25d7 b5fa7cae c6e9a4e7 ee2f3bc5 4a2fca10 aeed39c7 */
    #if defined(REMU_STOP_AFTER) && REMU_STOP_AFTER == 12
    #if defined(REMU_RETURN_REGISTER)
    return r[REMU_RETURN_REGISTER];
    #elif defined(REMU_RETURN_MEMORY)
    return memory[REMU_RETURN_MEMORY];
    #else
    u32 checkpoint_result11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 6u; ++checkpoint_i11) checkpoint_result11 = (checkpoint_result11 << 5u) ^ (checkpoint_result11 >> 2u) ^ r[checkpoint_i11];
    #if defined(REMU_RETURN_REGISTER_DIGEST)
    return checkpoint_result11;
    #endif
    u32 checkpoint_memory11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 8u; ++checkpoint_i11) checkpoint_memory11 = (checkpoint_memory11 << 5u) ^ (checkpoint_memory11 >> 2u) ^ memory[checkpoint_i11];
    #if defined(REMU_RETURN_MEMORY_DIGEST)
    return checkpoint_memory11;
    #endif
    return checkpoint_result11 ^ (checkpoint_memory11 << 11u | checkpoint_memory11 >> 21u);
    #endif
    #endif
    /* reference final registers: 793b25d7 b5fa7cae c6e9a4e7 ee2f3bc5 4a2fca10 aeed39c7 */
    /* reference final memory: 31d3d0ec 53e282e3 4e7067ed 80000878 982efc1b 800021e0 c54dfa70 559bf365 */
    u32 result = 0x9e3779b9u;
    for (u32 i = 0u; i < 6u; ++i) result = (result << 5u) ^ (result >> 2u) ^ r[i];
    u32 memory_result = 0x9e3779b9u;
    for (u32 i = 0u; i < 8u; ++i) memory_result = (memory_result << 5u) ^ (memory_result >> 2u) ^ memory[i];
    return result ^ ((memory_result << 11u) | (memory_result >> 21u));
}
#endif
