/* Generated by renvo-casegen. Do not edit by hand.
* case: case_0234
* name: register-field-pack--reverse-loop-switch-phi-add-carry-0ea
* category: embedded-registers
* structural signature: reverse-loop,switch-phi,add-carry,endian-swap,minmax-clamp,carry-chain,reverse-loop,halfword-swap,byte-pack,rotate-mix,mask-merge,counted-loop
* inspiration: https://github.com/embench/embench-iot
* kernel expected: 0x0001c2df
* expected: 0x331fb0f0
* Contract: freestanding ISO C unsigned arithmetic; no undefined behavior.
*/
typedef unsigned int u32;
typedef unsigned short u16;
typedef unsigned char u8;

static volatile u32 input[16] = { 0x80a3093cu, 0xa7857230u, 0x83dfc0f3u, 0x2815d4a4u, 0xd3c8254bu, 0xf1cdf4a1u, 0xde07c6b9u, 0x710deee6u, 0x065999efu, 0x80000000u, 0xbc3e0778u, 0x30c84527u, 0xe5d0fd2fu, 0x051a87a5u, 0x2d62fe67u, 0x56d8fe0bu };

__attribute__((noinline)) static u32 renvo_kernel(void)
{
    u32 packed = (input[0] & 0x1fu) | ((input[1] & 0x3ffu) << 5u) | ((input[2] & 0x1ffffu) << 15u);
    return (packed & 0x1fu) ^ ((packed >> 5u) & 0x3ffu) ^ ((packed >> 15u) & 0x1ffffu);
}

#ifdef RENVO_KERNEL_ONLY
__attribute__((noinline, used)) u32 renvo_case(void)
{
    return renvo_kernel();
}
#else
__attribute__((noinline, used)) u32 renvo_case(void)
{
    u32 r[6];
    u32 memory[8];
    r[0] = renvo_kernel();
    r[1] = input[11];
    r[2] = input[15];
    r[3] = input[3];
    r[4] = input[7];
    r[5] = 0x9eb5431au;
    memory[0] = input[0] ^ 0x000000eau;
    memory[1] = input[1] ^ 0x000001d4u;
    memory[2] = input[2] ^ 0x000003a8u;
    memory[3] = input[3] ^ 0x00000750u;
    memory[4] = input[4] ^ 0x00000ea0u;
    memory[5] = input[5] ^ 0x00001d40u;
    memory[6] = input[6] ^ 0x00003a80u;
    memory[7] = input[7] ^ 0x00007500u;
    u32 source0 = r[5], reversed0 = 0u; for (u32 i0 = 0u; i0 < 32u; ++i0) { reversed0 = (reversed0 << 1u) | (source0 & 1u); source0 >>= 1u; } r[1] = reversed0 ^ r[2];
    /* checkpoint 1: 1df02716; registers: 0001c2df 0e1a5372 56d8fe0b 2815d4a4 710deee6 9eb5431a */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 1
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 6u; ++checkpoint_i0) checkpoint_result0 = (checkpoint_result0 << 5u) ^ (checkpoint_result0 >> 2u) ^ r[checkpoint_i0];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result0;
    #endif
    u32 checkpoint_memory0 = 0x9e3779b9u;
    for (u32 checkpoint_i0 = 0u; checkpoint_i0 < 8u; ++checkpoint_i0) checkpoint_memory0 = (checkpoint_memory0 << 5u) ^ (checkpoint_memory0 >> 2u) ^ memory[checkpoint_i0];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory0;
    #endif
    return checkpoint_result0 ^ (checkpoint_memory0 << 11u | checkpoint_memory0 >> 21u);
    #endif
    #endif
    switch (r[5] & 3u) { case 0u: r[4] = r[4] + r[5]; break; case 1u: r[4] = r[4] - r[5]; break; case 2u: r[4] = r[4] ^ (r[5] << 5u | r[5] >> 27u); break; default: r[4] = r[4] * 3u ^ r[5]; break; }
    /* checkpoint 2: fd5655a2; registers: 0001c2df 0e1a5372 56d8fe0b 2815d4a4 a7a58db5 9eb5431a */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 2
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 6u; ++checkpoint_i1) checkpoint_result1 = (checkpoint_result1 << 5u) ^ (checkpoint_result1 >> 2u) ^ r[checkpoint_i1];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result1;
    #endif
    u32 checkpoint_memory1 = 0x9e3779b9u;
    for (u32 checkpoint_i1 = 0u; checkpoint_i1 < 8u; ++checkpoint_i1) checkpoint_memory1 = (checkpoint_memory1 << 5u) ^ (checkpoint_memory1 >> 2u) ^ memory[checkpoint_i1];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory1;
    #endif
    return checkpoint_result1 ^ (checkpoint_memory1 << 11u | checkpoint_memory1 >> 21u);
    #endif
    #endif
    u32 sum2 = r[3] + r[4]; r[5] = sum2 ^ (sum2 < r[3]);
    /* checkpoint 3: ac5874e1; registers: 0001c2df 0e1a5372 56d8fe0b 2815d4a4 a7a58db5 cfbb6259 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 3
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 6u; ++checkpoint_i2) checkpoint_result2 = (checkpoint_result2 << 5u) ^ (checkpoint_result2 >> 2u) ^ r[checkpoint_i2];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result2;
    #endif
    u32 checkpoint_memory2 = 0x9e3779b9u;
    for (u32 checkpoint_i2 = 0u; checkpoint_i2 < 8u; ++checkpoint_i2) checkpoint_memory2 = (checkpoint_memory2 << 5u) ^ (checkpoint_memory2 >> 2u) ^ memory[checkpoint_i2];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory2;
    #endif
    return checkpoint_result2 ^ (checkpoint_memory2 << 11u | checkpoint_memory2 >> 21u);
    #endif
    #endif
    u32 endian3 = ((r[2] & 0xffu) << 24u) | ((r[2] & 0xff00u) << 8u) | ((r[2] >> 8u) & 0xff00u) | (r[2] >> 24u); r[4] = endian3 ^ (r[5] << 8u | r[5] >> 24u);
    /* checkpoint 4: 4eb7b26a; registers: 0001c2df 0e1a5372 56d8fe0b 2815d4a4 b09c8199 cfbb6259 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 4
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 6u; ++checkpoint_i3) checkpoint_result3 = (checkpoint_result3 << 5u) ^ (checkpoint_result3 >> 2u) ^ r[checkpoint_i3];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result3;
    #endif
    u32 checkpoint_memory3 = 0x9e3779b9u;
    for (u32 checkpoint_i3 = 0u; checkpoint_i3 < 8u; ++checkpoint_i3) checkpoint_memory3 = (checkpoint_memory3 << 5u) ^ (checkpoint_memory3 >> 2u) ^ memory[checkpoint_i3];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory3;
    #endif
    return checkpoint_result3 ^ (checkpoint_memory3 << 11u | checkpoint_memory3 >> 21u);
    #endif
    #endif
    u32 low4 = r[2] < r[3] ? r[2] : r[3], high4 = r[2] > r[3] ? r[2] : r[3]; u32 clamp4 = r[1] < low4 ? low4 : (r[1] > high4 ? high4 : r[1]); r[1] = clamp4 ^ low4 ^ high4;
    /* checkpoint 5: e57f529f; registers: 0001c2df 56d8fe0b 56d8fe0b 2815d4a4 b09c8199 cfbb6259 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 5
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 6u; ++checkpoint_i4) checkpoint_result4 = (checkpoint_result4 << 5u) ^ (checkpoint_result4 >> 2u) ^ r[checkpoint_i4];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result4;
    #endif
    u32 checkpoint_memory4 = 0x9e3779b9u;
    for (u32 checkpoint_i4 = 0u; checkpoint_i4 < 8u; ++checkpoint_i4) checkpoint_memory4 = (checkpoint_memory4 << 5u) ^ (checkpoint_memory4 >> 2u) ^ memory[checkpoint_i4];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory4;
    #endif
    return checkpoint_result4 ^ (checkpoint_memory4 << 11u | checkpoint_memory4 >> 21u);
    #endif
    #endif
    u32 low5 = r[3] + r[1], carry5 = low5 < r[3]; u32 high5 = r[0] + r[1] + carry5; r[0] = low5 ^ high5;
    /* checkpoint 6: 7713a469; registers: 28341245 56d8fe0b 56d8fe0b 2815d4a4 b09c8199 cfbb6259 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 6
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 6u; ++checkpoint_i5) checkpoint_result5 = (checkpoint_result5 << 5u) ^ (checkpoint_result5 >> 2u) ^ r[checkpoint_i5];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result5;
    #endif
    u32 checkpoint_memory5 = 0x9e3779b9u;
    for (u32 checkpoint_i5 = 0u; checkpoint_i5 < 8u; ++checkpoint_i5) checkpoint_memory5 = (checkpoint_memory5 << 5u) ^ (checkpoint_memory5 >> 2u) ^ memory[checkpoint_i5];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory5;
    #endif
    return checkpoint_result5 ^ (checkpoint_memory5 << 11u | checkpoint_memory5 >> 21u);
    #endif
    #endif
    u32 source6 = r[5], reversed6 = 0u; for (u32 i6 = 0u; i6 < 32u; ++i6) { reversed6 = (reversed6 << 1u) | (source6 & 1u); source6 >>= 1u; } r[1] = reversed6 ^ r[4];
    /* checkpoint 7: 1d7f869b; registers: 28341245 2ada5c6a 56d8fe0b 2815d4a4 b09c8199 cfbb6259 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 7
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 6u; ++checkpoint_i6) checkpoint_result6 = (checkpoint_result6 << 5u) ^ (checkpoint_result6 >> 2u) ^ r[checkpoint_i6];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result6;
    #endif
    u32 checkpoint_memory6 = 0x9e3779b9u;
    for (u32 checkpoint_i6 = 0u; checkpoint_i6 < 8u; ++checkpoint_i6) checkpoint_memory6 = (checkpoint_memory6 << 5u) ^ (checkpoint_memory6 >> 2u) ^ memory[checkpoint_i6];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory6;
    #endif
    return checkpoint_result6 ^ (checkpoint_memory6 << 11u | checkpoint_memory6 >> 21u);
    #endif
    #endif
    r[2] = (r[3] << 16u | r[3] >> 16u) ^ (r[2] & 0xffff0000u);
    /* checkpoint 8: d8bda5e7; registers: 28341245 2ada5c6a 827c2815 2815d4a4 b09c8199 cfbb6259 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 8
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 6u; ++checkpoint_i7) checkpoint_result7 = (checkpoint_result7 << 5u) ^ (checkpoint_result7 >> 2u) ^ r[checkpoint_i7];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result7;
    #endif
    u32 checkpoint_memory7 = 0x9e3779b9u;
    for (u32 checkpoint_i7 = 0u; checkpoint_i7 < 8u; ++checkpoint_i7) checkpoint_memory7 = (checkpoint_memory7 << 5u) ^ (checkpoint_memory7 >> 2u) ^ memory[checkpoint_i7];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory7;
    #endif
    return checkpoint_result7 ^ (checkpoint_memory7 << 11u | checkpoint_memory7 >> 21u);
    #endif
    #endif
    r[4] = (r[5] & 0xffu) | ((r[0] & 0xffu) << 8u) | (((r[5] >> 8u) & 0xffu) << 16u) | (((r[0] >> 8u) & 0xffu) << 24u);
    /* checkpoint 9: afda8cd7; registers: 28341245 2ada5c6a 827c2815 2815d4a4 12624559 cfbb6259 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 9
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 6u; ++checkpoint_i8) checkpoint_result8 = (checkpoint_result8 << 5u) ^ (checkpoint_result8 >> 2u) ^ r[checkpoint_i8];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result8;
    #endif
    u32 checkpoint_memory8 = 0x9e3779b9u;
    for (u32 checkpoint_i8 = 0u; checkpoint_i8 < 8u; ++checkpoint_i8) checkpoint_memory8 = (checkpoint_memory8 << 5u) ^ (checkpoint_memory8 >> 2u) ^ memory[checkpoint_i8];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory8;
    #endif
    return checkpoint_result8 ^ (checkpoint_memory8 << 11u | checkpoint_memory8 >> 21u);
    #endif
    #endif
    u32 shift9 = r[0] & 31u; r[5] = (shift9 == 0u ? r[2] : (r[2] << shift9) | (r[2] >> (32u - shift9))) ^ (((shift9 + 7u) & 31u) == 0u ? r[0] : (r[0] >> ((shift9 + 7u) & 31u)) | (r[0] << (32u - ((shift9 + 7u) & 31u))));
    /* checkpoint 10: 0bb66f7f; registers: 28341245 2ada5c6a 827c2815 2815d4a4 12624559 6bd781f1 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 10
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 6u; ++checkpoint_i9) checkpoint_result9 = (checkpoint_result9 << 5u) ^ (checkpoint_result9 >> 2u) ^ r[checkpoint_i9];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result9;
    #endif
    u32 checkpoint_memory9 = 0x9e3779b9u;
    for (u32 checkpoint_i9 = 0u; checkpoint_i9 < 8u; ++checkpoint_i9) checkpoint_memory9 = (checkpoint_memory9 << 5u) ^ (checkpoint_memory9 >> 2u) ^ memory[checkpoint_i9];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory9;
    #endif
    return checkpoint_result9 ^ (checkpoint_memory9 << 11u | checkpoint_memory9 >> 21u);
    #endif
    #endif
    u32 mask10 = (r[4] << 13u) | (r[4] >> 19u); r[0] = (r[4] & mask10) | (r[2] & ~mask10);
    /* checkpoint 11: aba4dd7b; registers: 82760859 2ada5c6a 827c2815 2815d4a4 12624559 6bd781f1 */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 11
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 6u; ++checkpoint_i10) checkpoint_result10 = (checkpoint_result10 << 5u) ^ (checkpoint_result10 >> 2u) ^ r[checkpoint_i10];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result10;
    #endif
    u32 checkpoint_memory10 = 0x9e3779b9u;
    for (u32 checkpoint_i10 = 0u; checkpoint_i10 < 8u; ++checkpoint_i10) checkpoint_memory10 = (checkpoint_memory10 << 5u) ^ (checkpoint_memory10 >> 2u) ^ memory[checkpoint_i10];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory10;
    #endif
    return checkpoint_result10 ^ (checkpoint_memory10 << 11u | checkpoint_memory10 >> 21u);
    #endif
    #endif
    u32 loop11 = r[4]; for (u32 i11 = 0u; i11 < 4u; ++i11) { loop11 += r[3] ^ i11; loop11 = loop11 << 3u | loop11 >> 29u; } r[5] = loop11;
    /* checkpoint 12: 331fb0f0; registers: 82760859 2ada5c6a 827c2815 2815d4a4 12624559 f36cec7a */
    #if defined(RENVO_STOP_AFTER) && RENVO_STOP_AFTER == 12
    #if defined(RENVO_RETURN_REGISTER)
    return r[RENVO_RETURN_REGISTER];
    #elif defined(RENVO_RETURN_MEMORY)
    return memory[RENVO_RETURN_MEMORY];
    #else
    u32 checkpoint_result11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 6u; ++checkpoint_i11) checkpoint_result11 = (checkpoint_result11 << 5u) ^ (checkpoint_result11 >> 2u) ^ r[checkpoint_i11];
    #if defined(RENVO_RETURN_REGISTER_DIGEST)
    return checkpoint_result11;
    #endif
    u32 checkpoint_memory11 = 0x9e3779b9u;
    for (u32 checkpoint_i11 = 0u; checkpoint_i11 < 8u; ++checkpoint_i11) checkpoint_memory11 = (checkpoint_memory11 << 5u) ^ (checkpoint_memory11 >> 2u) ^ memory[checkpoint_i11];
    #if defined(RENVO_RETURN_MEMORY_DIGEST)
    return checkpoint_memory11;
    #endif
    return checkpoint_result11 ^ (checkpoint_memory11 << 11u | checkpoint_memory11 >> 21u);
    #endif
    #endif
    /* reference final registers: 82760859 2ada5c6a 827c2815 2815d4a4 12624559 f36cec7a */
    /* reference final memory: 80a309d6 a78573e4 83dfc35b 2815d3f4 d3c82beb f1cde9e1 de07fc39 710d9be6 */
    u32 result = 0x9e3779b9u;
    for (u32 i = 0u; i < 6u; ++i) result = (result << 5u) ^ (result >> 2u) ^ r[i];
    u32 memory_result = 0x9e3779b9u;
    for (u32 i = 0u; i < 8u; ++i) memory_result = (memory_result << 5u) ^ (memory_result >> 2u) ^ memory[i];
    return result ^ ((memory_result << 11u) | (memory_result >> 21u));
}
#endif
