[package]
name = "remu-cpu-msp430"
description = "Interpreted MSP430X CPU for Renvo Emulator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
remu-core.workspace = true
serde.workspace = true

[dev-dependencies]
remu-bus.workspace = true

[lints]
workspace = true
