name = "gcc-13-riscv-batch"
image = "sha256:8f78d0ea26f75e5b44c2ad88175202f66f1e7054c6ec695c72d26948a48ba736"
program = "sh"
args = ["support/build-riscv.sh"]

[environment]
LC_ALL = "C"
SOURCE_DATE_EPOCH = "0"
