name = "clang-18-riscv-batch"
image = "sha256:e31d07e59ec7eb7f05396e787db55127783b8a21bc2e907ebcaef6534d343dac"
local_image = "remu/cross-llvm:local"
program = "sh"
args = ["support/build-riscv-clang.sh"]

[environment]
LC_ALL = "C"
SOURCE_DATE_EPOCH = "0"
