name = "ti-msp430-gcc-9.3.1.11-support-1.212"
image = "sha256:c2da13329a24c10f764d480b9aeef07d31cc20f77c2040dfedd2cfe9942dbeb2"
local_image = "renvo/msp430-gcc:local"
program = "msp430-elf-gcc"
args = [
    "-mmcu=msp430fr2433",
    "-mhwmult=none",
    "-I/opt/ti/msp430-gcc-support-files/include",
    "-L/opt/ti/msp430-gcc-support-files/include",
    "-T/opt/ti/msp430-gcc-support-files/include/msp430fr2433.ld",
    "-ffreestanding",
]

[environment]
LC_ALL = "C"
SOURCE_DATE_EPOCH = "0"
