name = "gcc-13-rv32imac-ilp32"
image = "sha256:8f78d0ea26f75e5b44c2ad88175202f66f1e7054c6ec695c72d26948a48ba736"
program = "riscv64-unknown-elf-gcc"
args = [
    "-march=rv32imac_zicsr",
    "-mabi=ilp32",
    "-ffreestanding",
    "-nostdlib",
]

[environment]
LC_ALL = "C"
SOURCE_DATE_EPOCH = "0"
