name = "gcc-13-rv32ec-ilp32e"
image = "sha256:8f78d0ea26f75e5b44c2ad88175202f66f1e7054c6ec695c72d26948a48ba736"
local_image = "renvo/cross-gcc:local"
program = "riscv64-unknown-elf-gcc"
args = [
    "-march=rv32ec_zicsr",
    "-mabi=ilp32e",
    "-ffreestanding",
    "-nostdlib",
    "-Wl,--build-id=none,--discard-all",
]

[environment]
LC_ALL = "C"
SOURCE_DATE_EPOCH = "0"
