[package]
name = "renvo-cpu-pic16"
description = "Interpreted enhanced mid-range PIC16 CPU for Renvo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
renvo-bus.workspace = true
renvo-core.workspace = true
serde.workspace = true

[lints]
workspace = true
