[package]
name = "renvo-cpu-xtensa"
description = "Interpreted Xtensa LX7 CPU for Renvo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
renvo-core.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
renvo-bus.workspace = true

[lints]
workspace = true
