//! Reusable functional microcontroller peripheral models.

use remu_bus::{Device, DeviceError};
use remu_core::{AccessWidth, ResetKind, SimTime};
use remu_signals::{
    DigitalNet, DriverId, Logic, SignalChange, SignalError, SignalId, SignalRegistry, SignalValue,
};
use std::cell::{Cell, RefCell};
use std::collections::{BTreeMap, BTreeSet, VecDeque};
use std::rc::Rc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};

mod signals;
pub use signals::*;
mod uart;
pub use uart::*;
mod i2c;
pub use i2c::*;
mod pwm;
pub use pwm::*;
mod spi;
pub use spi::*;
mod wch;
pub use wch::*;
mod wch_adc;
pub use wch_adc::*;
mod wch_watchdog;
pub use wch_watchdog::*;
mod wch_flash;
pub use wch_flash::*;
mod wch_dma;
pub use wch_dma::*;
mod wch_i2c;
pub use wch_i2c::*;
mod esp_usb_serial_jtag;
pub use esp_usb_serial_jtag::*;
mod gpio;
pub use gpio::*;
mod rp_pio;
pub use rp_pio::*;
mod rp;
pub use rp::*;
mod rp_io;
pub use rp_io::*;
mod rp_pads;
pub use rp_pads::*;
mod rp_i2c;
pub use rp_i2c::*;
mod esp_usb_otg_register;
pub use esp_usb_otg_register::*;
mod rp_adc;
pub use rp_adc::*;
mod rp_power;
pub use rp_power::*;
mod rp_trng;
pub use rp_trng::*;
mod rp_sha;
pub use rp_sha::*;
mod rp_hstx;
pub use rp_hstx::*;
mod rp_otp;
pub use rp_otp::*;
mod rp_accessctrl;
pub use rp_accessctrl::*;
mod rp_ticks;
pub use rp_ticks::*;
mod rp_powman;
pub use rp_powman::*;
mod rp_dma;
pub use rp_dma::*;
mod esp;
pub use esp::*;
mod esp_spi;
pub use esp_spi::*;
mod esp_i2c;
pub use esp_i2c::*;
mod esp_c6_i2s;
pub use esp_c6_i2s::*;
mod esp_c6_rmt;
pub use esp_c6_rmt::*;
mod esp_c6_ledc;
pub use esp_c6_ledc::*;
mod esp_c6_pcnt;
pub use esp_c6_pcnt::*;
mod esp_c6_mcpwm;
pub use esp_c6_mcpwm::*;
mod esp_c6_twai;
pub use esp_c6_twai::*;
mod esp_c6_gdma;
pub use esp_c6_gdma::*;
mod esp_c6_saradc;
pub use esp_c6_saradc::*;
mod esp32s3_ble_lp_clock;
mod esp32s3_radio;
mod esp_c6_cache;
mod esp_c6_interrupt;
mod esp_c6_power;
mod esp_c6_radio;
mod esp_c6_security;
mod esp_c6_sha;
mod esp_c6_system;
mod esp_wifi_common;
pub use esp_c6_cache::*;
pub use esp_c6_interrupt::*;
pub use esp_c6_power::*;
pub use esp_c6_radio::*;
pub use esp_c6_security::*;
pub use esp_c6_sha::*;
pub use esp_c6_system::*;
pub use esp_wifi_common::*;
pub use esp32s3_ble_lp_clock::*;
pub use esp32s3_radio::*;
mod esp_c6_aes;
pub use esp_c6_aes::*;
mod esp_c6_hmac;
pub use esp_c6_hmac::*;
mod esp_etm;
pub use esp_etm::*;
mod esp_parlio;
pub use esp_parlio::*;
mod esp_lp_uart;
pub use esp_lp_uart::*;
mod esp_lp_i2c;
pub use esp_lp_i2c::*;
mod esp_lp_wdt;
pub use esp_lp_wdt::*;
mod esp_sdio;
pub use esp_sdio::*;
mod esp_i2c_s3;
pub use esp_i2c_s3::*;
mod esp_spi_gp;
pub use esp_spi_gp::*;
mod esp_i2s;
pub use esp_i2s::*;
mod esp_rmt;
pub use esp_rmt::*;
mod esp_ledc;
pub use esp_ledc::*;
mod esp_pcnt;
pub use esp_pcnt::*;
mod esp_mcpwm;
pub use esp_mcpwm::*;
mod esp_twai;
pub use esp_twai::*;
mod esp_gdma;
pub use esp_gdma::*;
mod esp_saradc;
pub use esp_saradc::*;
mod esp_tsens;
pub use esp_tsens::*;
mod esp_lcd_cam;
pub use esp_lcd_cam::*;
mod esp_sdmmc;
pub use esp_sdmmc::*;
mod esp_sha;
pub use esp_sha::*;
mod esp_aes;
pub use esp_aes::*;
mod esp_efuse;
pub use esp_efuse::*;
mod esp_hmac;
pub use esp_hmac::*;
mod esp_rsa;
pub use esp_rsa::*;
mod esp_digital_signature;
pub use esp_digital_signature::*;
mod esp_rtc;
pub use esp_rtc::*;
mod esp_interrupt_matrix;
pub use esp_interrupt_matrix::*;
mod esp_io_mux;
pub use esp_io_mux::*;
mod esp_uhci;
pub use esp_uhci::*;
mod esp_syscon;
pub use esp_syscon::*;
mod esp_usb_wrap;
pub use esp_usb_wrap::*;
mod esp_pms;
pub use esp_pms::*;
mod esp_world_controller;
pub use esp_world_controller::*;
mod esp_extmem;
pub use esp_extmem::*;
mod esp_rtc_i2c;
pub use esp_rtc_i2c::*;
mod esp_xts_aes;
pub use esp_xts_aes::*;
mod esp_sdm;
pub use esp_sdm::*;
mod esp_rtc_io;
pub use esp_rtc_io::*;
mod esp_peri_backup;
pub use esp_peri_backup::*;
mod esp_assist_debug;
pub use esp_assist_debug::*;
mod arm;
pub use arm::*;
mod rp2350_spi;
pub use rp2350_spi::*;
mod esp_gpio;
pub use esp_gpio::*;
mod functional;
pub use functional::*;
mod samd;
pub use samd::*;
mod samd_evsys;
pub use samd_evsys::*;
mod samd_usb;
pub use samd_usb::*;
mod samd_dmac;
pub use samd_dmac::*;
mod samd_i2s;
pub use samd_i2s::*;
mod samd_adc;
pub use samd_adc::*;
mod samd_ac;
pub use samd_ac::*;
mod samd_timers;
pub use samd_timers::*;
mod samd_wdt;
pub use samd_wdt::*;
mod stm32;
pub use stm32::*;
mod ra;
pub use ra::*;
mod avr;
pub use avr::*;
mod msp430;
pub use msp430::*;
mod pic16;
pub use pic16::*;
mod efm8;
pub use efm8::*;
mod board_components;
pub use board_components::*;

#[cfg(test)]
mod tests;
