//! Reusable functional microcontroller peripheral models.

use remu_bus::{Device, DeviceError};
use remu_core::{AccessWidth, ResetKind, SimTime};
use remu_signals::{
    DigitalNet, DriverId, Logic, SignalChange, SignalError, SignalId, SignalRegistry, SignalValue,
};
use std::cell::RefCell;
use std::collections::{BTreeMap, VecDeque};
use std::rc::Rc;
use std::sync::{Arc, Mutex};

mod signals;
pub use signals::*;
mod uart;
pub use uart::*;
mod wch;
pub use wch::*;
mod wch_flash;
pub use wch_flash::*;
mod esp_usb_serial_jtag;
pub use esp_usb_serial_jtag::*;
mod gpio;
pub use gpio::*;
mod rp;
pub use rp::*;
mod esp_usb_otg_register;
pub use esp_usb_otg_register::*;
mod esp;
pub use esp::*;
mod esp_i2c_s3;
pub use esp_i2c_s3::*;
mod esp_spi_gp;
pub use esp_spi_gp::*;
mod esp_i2s;
pub use esp_i2s::*;
mod esp_rmt;
pub use esp_rmt::*;
mod esp_ledc;
pub use esp_ledc::*;
mod esp_pcnt;
pub use esp_pcnt::*;
mod esp_mcpwm;
pub use esp_mcpwm::*;
mod esp_twai;
pub use esp_twai::*;
mod esp_gdma;
pub use esp_gdma::*;
mod esp_saradc;
pub use esp_saradc::*;
mod esp_tsens;
pub use esp_tsens::*;
mod esp_lcd_cam;
pub use esp_lcd_cam::*;
mod esp_sdmmc;
pub use esp_sdmmc::*;
mod esp_sha;
pub use esp_sha::*;
mod esp_aes;
pub use esp_aes::*;
mod esp_efuse;
pub use esp_efuse::*;
mod esp_hmac;
pub use esp_hmac::*;
mod esp_rsa;
pub use esp_rsa::*;
mod esp_digital_signature;
pub use esp_digital_signature::*;
mod esp_rtc;
pub use esp_rtc::*;
mod esp_interrupt_matrix;
pub use esp_interrupt_matrix::*;
mod esp_io_mux;
pub use esp_io_mux::*;
mod esp_uhci;
pub use esp_uhci::*;
mod esp_syscon;
pub use esp_syscon::*;
mod esp_usb_wrap;
pub use esp_usb_wrap::*;
mod esp_pms;
pub use esp_pms::*;
mod esp_world_controller;
pub use esp_world_controller::*;
mod esp_extmem;
pub use esp_extmem::*;
mod esp_rtc_i2c;
pub use esp_rtc_i2c::*;
mod esp_xts_aes;
pub use esp_xts_aes::*;
mod esp_sdm;
pub use esp_sdm::*;
mod esp_rtc_io;
pub use esp_rtc_io::*;
mod esp_peri_backup;
pub use esp_peri_backup::*;
mod esp_assist_debug;
pub use esp_assist_debug::*;
mod arm;
pub use arm::*;
mod esp_gpio;
pub use esp_gpio::*;
mod functional;
pub use functional::*;
mod samd;
pub use samd::*;
mod stm32;
pub use stm32::*;
mod ra;
pub use ra::*;
mod avr;
pub use avr::*;
mod msp430;
pub use msp430::*;
mod pic16;
pub use pic16::*;
mod efm8;
pub use efm8::*;
mod board_components;
pub use board_components::*;

#[cfg(test)]
mod tests;
