[package]
name = "renvo-machines"
description = "Microcontroller and board models for Renvo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
md-5.workspace = true
renvo-bus.workspace = true
renvo-core.workspace = true
renvo-cpu-arm.workspace = true
renvo-cpu-riscv.workspace = true
renvo-cpu-xtensa.workspace = true
renvo-devices.workspace = true
renvo-image.workspace = true
renvo-signals.workspace = true
renvo-trace.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true

[lints]
workspace = true
