[package]
name = "renvo-gdb"
description = "GDB Remote Serial Protocol adapter for Renvo machines"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hex.workspace = true
renvo-core.workspace = true
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
