[package]
name = "renvo-cpu-riscv"
description = "Profile-driven interpreted RISC-V CPU for Renvo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
renvo-core.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
renvo-bus.workspace = true

[lints]
workspace = true
