[package]
name = "renvo-cpu-mcs51"
description = "Reusable interpreted MCS-51 CPU for Renvo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
renvo-bus.workspace = true
renvo-core.workspace = true
serde.workspace = true

[lints]
workspace = true
